### ISSUE TITLE
Elements class structure

### ISSUE THREAD

**Issue by jeanluc-auge** [Telecominfraproject/oopt-gnpy#100]
Can we think of a better __init__ structure than the extensive use of namedtuple we are having?
[init class EDFA](https://github.com/Telecominfraproject/oopt-gnpy/blob/9839681bc05c17c4320f3602f8d8868bbd14afd2/gnpy/core/elements.py#L322)
I have several issues with these namedtuple. For example in the EDFA class:
* the params parameter cannot be skipped because it will require the EDFAparams positional arguments: the None default value in __init__ is not working by the way.
* the params cannot be updated after the calss creation because namedtuple are unmutable. As a result I have (for example): edfa.con_in != edfa.params.con_in in some instances
* most importantly we lost the flexiblity of the initial class structure where there was no need to update the code when adding a new parameter in the json input files. now you need to update several namedtupple and you lose compatibility with previous json files.

**Comment by dutc** [comment]
Discussed on July 31 Coder's Call (on Workplace.) 

No immediate action items.

**Comment by ggrammel** [comment]
2018-10-23: we leave issue closed but expect it to come up soon with a pull request by JL/Esther
