### ISSUE TITLE
python setup.py install  is failing on my environment

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#103]
I have tried on my ubuntu 17.10 to run the  python3 setup.py install, but it fails (see attached file). I have also tried on a debian with the same result.

pip3 install -r requirement.txt                  runs succesfully instead.

can we add this alternative on the README file  ?
[record_install.txt](https://github.com/Telecominfraproject/oopt-gnpy/files/2340690/record_install.txt)

**Comment by dutc** [comment]
Can you give more information about your user environment?

`which pip3 python3`

**Comment by dutc** [comment]
I'll try on a clean Ubuntu 18.04 and report.

**Comment by EstherLerouzic** [comment]
versions :  pip 9.0.1 , Python3.6.3

**Comment by dutc** [comment]
Fixed in version 1.0.
