### ISSUE TITLE
Readme test: Following description produces failures

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#105]
The aim is to run through Readme.md and check if it sufficiently describes the necessary steps to run the code. The Description SHALL be fixed before it goes in main branch.
There is extensive output in the description aiming to ease debugging. For a quick check look for the keyword **FAIL**

1. Before starting:
env:
`
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/zk/gn06x9b11pn8ddjrg680m3jm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.a6XnPXL9wL/Render
TERM_PROGRAM_VERSION=388.1.2
OLDPWD=/projects/github
TERM_SESSION_ID=89B74D31-1873-4E10-A1A3-10CA5C037D68
USER=ggrammel
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.WwB0iI5iBx/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/projects/github/testing
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/ggrammel
LOGNAME=ggrammel
_=/usr/bin/env
`
$PWD
`
/projects/github/testing
`
$PYTHONPATH
empty

2. installation: 
2.1 using the first option
2.1.1 `pip3 install gnpy' --> **SUCCESS**
`
pip3 install gnpy
Requirement already satisfied: gnpy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (0.1.3)
Requirement already satisfied: py==1.5.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.5.2)
Requirement already satisfied: numpy==1.13.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.13.3)
Requirement already satisfied: pybtex==0.21 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.21)
Requirement already satisfied: Jinja2==2.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.10)
Requirement already satisfied: matplotlib==2.1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.1.0)
Requirement already satisfied: imagesize==0.7.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.7.1)
Requirement already satisfied: requests==2.18.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.18.4)
Requirement already satisfied: networkx==2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.0)
Requirement already satisfied: pytest==3.3.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (3.3.2)
Requirement already satisfied: decorator==4.1.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (4.1.2)
Requirement already satisfied: scipy==1.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.0.0)
Requirement already satisfied: snowballstemmer==1.2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.2.1)
Requirement already satisfied: six==1.11.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.11.0)
Requirement already satisfied: chardet==3.0.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (3.0.4)
Requirement already satisfied: pluggy==0.6.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.6.0)
Requirement already satisfied: idna==2.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.6)
Requirement already satisfied: Babel==2.5.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.5.3)
Requirement already satisfied: xlrd==1.1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.1.0)
Requirement already satisfied: MarkupSafe==1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.0)
Requirement already satisfied: PyYAML==3.12 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (3.12)
Requirement already satisfied: sphinxcontrib-websupport==1.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.0.1)
Requirement already satisfied: certifi==2017.11.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2017.11.5)
Requirement already satisfied: pybtex-docutils==0.2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.2.1)
Requirement already satisfied: pyparsing==2.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.2.0)
Requirement already satisfied: urllib3==1.22 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.22)
Requirement already satisfied: alabaster==0.7.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.7.10)
Requirement already satisfied: Sphinx==1.6.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.6.6)
Requirement already satisfied: oset==0.1.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.1.3)
Requirement already satisfied: Pygments==2.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.2.0)
Requirement already satisfied: python-dateutil==2.6.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2.6.1)
Requirement already satisfied: cycler==0.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.10.0)
Requirement already satisfied: attrs==17.4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (17.4.0)
Requirement already satisfied: docutils==0.14 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.14)
Requirement already satisfied: latexcodec==1.0.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (1.0.5)
Requirement already satisfied: sphinxcontrib-bibtex==0.3.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (0.3.6)
Requirement already satisfied: pytz==2017.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gnpy) (2017.3)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest==3.3.2->gnpy) (38.5.1)
`
2.1.2 skipping alternative installation procedure and continuing with 'To get started, run the transmission example:'

2.1.3 running transmission example --> **FAIL**
`cd examples
-bash: cd: examples: No such file or directory
`
**setup.py did not create the examples directory and the procedure described is not operational. Suggestion is to remove it from the description**

2.2 performing the alternative procedure using the repo

2.2.1 Cloning oopt-gnpy --> **SUCCESS**
**NOTE** since we are testing the develop branch, git clone... needs to be modified as below
`git clone --single-branch -b develop https://github.com/telecominfraproject/oopt-gnpy/
Cloning into 'oopt-gnpy'...
remote: Counting objects: 1521, done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 1521 (delta 104), reused 116 (delta 68), pack-reused 1352
Receiving objects: 100% (1521/1521), 676.45 KiB | 563.00 KiB/s, done.
Resolving deltas: 100% (939/939), done.
`
2.2.2 change directory --> **SUCCESS**
`cd oopt-gnpy`

2.2.3 install oopt-gnpy --> **SUCCESS**
`python3 setup.py install
/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating gnpy.egg-info
writing gnpy.egg-info/PKG-INFO
writing dependency_links to gnpy.egg-info/dependency_links.txt
writing requirements to gnpy.egg-info/requires.txt
writing top-level names to gnpy.egg-info/top_level.txt
writing manifest file 'gnpy.egg-info/SOURCES.txt'
reading manifest file 'gnpy.egg-info/SOURCES.txt'
writing manifest file 'gnpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gnpy
copying gnpy/__init__.py -> build/lib/gnpy
creating build/lib/gnpy/core
copying gnpy/core/__init__.py -> build/lib/gnpy/core
copying gnpy/core/convert.py -> build/lib/gnpy/core
copying gnpy/core/elements.py -> build/lib/gnpy/core
copying gnpy/core/equipment.py -> build/lib/gnpy/core
copying gnpy/core/execute.py -> build/lib/gnpy/core
copying gnpy/core/info.py -> build/lib/gnpy/core
copying gnpy/core/network.py -> build/lib/gnpy/core
copying gnpy/core/node.py -> build/lib/gnpy/core
copying gnpy/core/request.py -> build/lib/gnpy/core
copying gnpy/core/units.py -> build/lib/gnpy/core
copying gnpy/core/utils.py -> build/lib/gnpy/core
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/gnpy
copying build/lib/gnpy/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy
creating build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/convert.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/elements.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/equipment.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/execute.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/info.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/network.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/node.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/request.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/units.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
copying build/lib/gnpy/core/utils.py -> build/bdist.macosx-10.7-x86_64/egg/gnpy/core
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/convert.py to convert.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/elements.py to elements.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/equipment.py to equipment.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/execute.py to execute.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/info.py to info.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/network.py to network.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/node.py to node.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/request.py to request.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/units.py to units.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/gnpy/core/utils.py to utils.cpython-36.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying gnpy.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying gnpy.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying gnpy.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying gnpy.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying gnpy.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/gnpy-0.1.3-py3.6.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing gnpy-0.1.3-py3.6.egg
Removing /anaconda3/lib/python3.6/site-packages/gnpy-0.1.3-py3.6.egg
Copying gnpy-0.1.3-py3.6.egg to /anaconda3/lib/python3.6/site-packages
gnpy 0.1.3 is already the active version in easy-install.pth

Installed /anaconda3/lib/python3.6/site-packages/gnpy-0.1.3-py3.6.egg
Processing dependencies for gnpy==0.1.3
Searching for xlrd==1.1.0
Best match: xlrd 1.1.0
Adding xlrd 1.1.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for sphinxcontrib-websupport==1.0.1
Best match: sphinxcontrib-websupport 1.0.1
Adding sphinxcontrib-websupport 1.0.1 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for sphinxcontrib-bibtex==0.3.6
Best match: sphinxcontrib-bibtex 0.3.6
Processing sphinxcontrib_bibtex-0.3.6-py3.6.egg
sphinxcontrib-bibtex 0.3.6 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/sphinxcontrib_bibtex-0.3.6-py3.6.egg
Searching for Sphinx==1.6.6
Best match: Sphinx 1.6.6
Processing Sphinx-1.6.6-py3.6.egg
Sphinx 1.6.6 is already the active version in easy-install.pth
Installing sphinx-apidoc script to /anaconda3/bin
Installing sphinx-autogen script to /anaconda3/bin
Installing sphinx-build script to /anaconda3/bin
Installing sphinx-quickstart script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages/Sphinx-1.6.6-py3.6.egg
Searching for snowballstemmer==1.2.1
Best match: snowballstemmer 1.2.1
Adding snowballstemmer 1.2.1 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for scipy==1.0.0
Best match: scipy 1.0.0
Processing scipy-1.0.0-py3.6-macosx-10.7-x86_64.egg
scipy 1.0.0 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/scipy-1.0.0-py3.6-macosx-10.7-x86_64.egg
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Processing pytz-2017.3-py3.6.egg
pytz 2017.3 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/pytz-2017.3-py3.6.egg
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Processing python_dateutil-2.6.1-py3.6.egg
python-dateutil 2.6.1 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/python_dateutil-2.6.1-py3.6.egg
Searching for pytest==3.3.2
Best match: pytest 3.3.2
Processing pytest-3.3.2-py3.6.egg
pytest 3.3.2 is already the active version in easy-install.pth
Installing py.test script to /anaconda3/bin
Installing pytest script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages/pytest-3.3.2-py3.6.egg
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for Pygments==2.2.0
Best match: Pygments 2.2.0
Adding Pygments 2.2.0 to easy-install.pth file
Installing pygmentize script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages
Searching for pybtex-docutils==0.2.1
Best match: pybtex-docutils 0.2.1
Processing pybtex_docutils-0.2.1-py3.6.egg
pybtex-docutils 0.2.1 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/pybtex_docutils-0.2.1-py3.6.egg
Searching for pybtex==0.21
Best match: pybtex 0.21
Processing pybtex-0.21-py3.6.egg
pybtex 0.21 is already the active version in easy-install.pth
Installing pybtex script to /anaconda3/bin
Installing pybtex-convert script to /anaconda3/bin
Installing pybtex-format script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages/pybtex-0.21-py3.6.egg
Searching for py==1.5.2
Best match: py 1.5.2
Processing py-1.5.2-py3.6.egg
py 1.5.2 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/py-1.5.2-py3.6.egg
Searching for pluggy==0.6.0
Best match: pluggy 0.6.0
Adding pluggy 0.6.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for oset==0.1.3
Best match: oset 0.1.3
Processing oset-0.1.3-py3.6.egg
oset 0.1.3 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/oset-0.1.3-py3.6.egg
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Processing numpy-1.13.3-py3.6-macosx-10.7-x86_64.egg
numpy 1.13.3 is already the active version in easy-install.pth
Installing f2py script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages/numpy-1.13.3-py3.6-macosx-10.7-x86_64.egg
Searching for networkx==2.0
Best match: networkx 2.0
Processing networkx-2.0-py3.6.egg
networkx 2.0 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/networkx-2.0-py3.6.egg
Searching for matplotlib==2.1.0
Best match: matplotlib 2.1.0
Processing matplotlib-2.1.0-py3.6-macosx-10.7-x86_64.egg
matplotlib 2.1.0 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-macosx-10.7-x86_64.egg
Searching for MarkupSafe==1.0
Best match: MarkupSafe 1.0
Adding MarkupSafe 1.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for latexcodec==1.0.5
Best match: latexcodec 1.0.5
Processing latexcodec-1.0.5-py3.6.egg
latexcodec 1.0.5 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/latexcodec-1.0.5-py3.6.egg
Searching for Jinja2==2.10
Best match: Jinja2 2.10
Adding Jinja2 2.10 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for imagesize==0.7.1
Best match: imagesize 0.7.1
Processing imagesize-0.7.1-py3.6.egg
imagesize 0.7.1 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/imagesize-0.7.1-py3.6.egg
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for docutils==0.14
Best match: docutils 0.14
Adding docutils 0.14 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for decorator==4.1.2
Best match: decorator 4.1.2
Processing decorator-4.1.2-py3.6.egg
decorator 4.1.2 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/decorator-4.1.2-py3.6.egg
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages
Searching for certifi==2017.11.5
Best match: certifi 2017.11.5
Processing certifi-2017.11.5-py3.6.egg
certifi 2017.11.5 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/certifi-2017.11.5-py3.6.egg
Searching for Babel==2.5.3
Best match: Babel 2.5.3
Adding Babel 2.5.3 to easy-install.pth file
Installing pybabel script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages
Searching for attrs==17.4.0
Best match: attrs 17.4.0
Processing attrs-17.4.0-py3.6.egg
attrs 17.4.0 is already the active version in easy-install.pth

Using /anaconda3/lib/python3.6/site-packages/attrs-17.4.0-py3.6.egg
Searching for alabaster==0.7.10
Best match: alabaster 0.7.10
Adding alabaster 0.7.10 to easy-install.pth file

Using /anaconda3/lib/python3.6/site-packages
Searching for setuptools==39.1.0
Best match: setuptools 39.1.0
Adding setuptools 39.1.0 to easy-install.pth file
Installing easy_install script to /anaconda3/bin

Using /anaconda3/lib/python3.6/site-packages
Finished processing dependencies for gnpy==0.1.3
'

2.2.4 change directory --> **SUCCESS**
`cd examples`

2.2.5 trying Transmission_main_example --> **FAIL**
`python3 transmission_main_example.py
Traceback (most recent call last):
  File "transmission_main_example.py", line 23, in <module>
    from gnpy.core.request import Path_request, RequestParams, compute_constrained_path, propagate
  File "/anaconda3/lib/python3.6/site-packages/gnpy-0.1.3-py3.6.egg/gnpy/core/request.py", line 22, in <module>
ModuleNotFoundError: No module named 'examples'
`
**this error could have been avoided by informing the user about setting PYTHONPATH prior to suggesting running the example**

3. Re-trying by setting PYTHONPATH
`
export PYTHONPATH=$PYTHONPATH:$PWD
$ echo $PYTHONPATH 
:/projects/github/testing/oopt-gnpy
`
3.1 change directory --> **SUCCESS**
'cd examples`

3.2 running transmission_main_example --> **SUCCESS**
`
python3 transmission_main_example.py
Power mode is set to True
=> it can be modified in eqpt_config.json - Spans
Transceiver(uid='Site_B', osnr_ase_01nm=None, osnr_ase=None, osnr_nli=None, snr=None) delta power in:
-3dB

There are 1 fiber spans over 80000m between Site_A and Site_B

Now propagating between Site_A and Site_B:
[0]

Propagating with input power = 0.00dBm :
Transceiver Site_A
Fiber          Span1
  type_variety:                SSMF
  length (km):                 80.00
  pad att_in (dB):             0.00
  total loss (dB):             16.00
  (includes conn loss (dB) in: 0.00 out: 0.00)
  (conn loss out includes EOL margin defined in eqpt_config.json)
Edfa Edfa1
  type_variety:           std_low_gain
  target gain (dB):       16.00
  effective gain(dB):     16.00
  noise figure (dB):      6.57
  including att_in
  pad att_in (dB):        0.00
  Power In (dBm):         2.81
  Power Out (dBm):        18.82
  Delta_P (dB):           0.0
  target pch (dBm):       0.0
  effective pch (dBm):    0.0
  output VOA (dB):        0.00
Transceiver Site_B
  OSNR ASE (1nm):        35.38
  OSNR ASE (signal bw):  31.30
  SNR total (signal bw): 27.71

Transmission result for input power = 0.00dBm :
Transceiver Site_B
  OSNR ASE (1nm):        35.38
  OSNR ASE (signal bw):  31.30
  SNR total (signal bw): 27.71
`
3.3 running Coronet example --> **FAIL**
'
python3 transmission_main_example.py coronet_conus_example.json
Traceback (most recent call last):
  File "transmission_main_example.py", line 108, in <module>
    network = load_network(args.filename, equipment)
  File "/projects/github/testing/oopt-gnpy/gnpy/core/network.py", line 36, in load_network
    json_data = load_json(json_filename)
  File "/projects/github/testing/oopt-gnpy/gnpy/core/utils.py", line 20, in load_json
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'coronet_conus_example.json'
'

checking directory content of ./examples shows that there is no coronet_conus_example. json present:
`
ls 
CORONET_Global_Topology.json		eqpt_config.json
CORONET_Global_Topology.xls		fused_roadm_example_network.json
Transmission Main Example.ipynb		meshTopologyExampleV2.json
__pycache__				meshTopologyExampleV2.xls
convert_service_sheet.py		meshTopologyExampleV2_services.json
create_eqpt_sheet.py			path_requests_run.py
default_edfa_config.json		std_medium_gain_advanced_config.json
edfa					transmission_main_example.py
edfa_example_network.json		write_path_jsontocsv.py
edfa_model
`
**Note:** the name may have been changed to CORONET_Global_Topology.json and we give this a try:
`
transmission_main_example.py CORONET_Global_Topology.json 
Power mode is set to True
...
`
***Note: Readme shall be updated to reflect new filename**

3.4 Running next example -->**FAIL**
`
python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2_services.json eqpt_file -o output_file.json
Traceback (most recent call last):
  File "path_requests_run.py", line 133, in <module>
    equipment = load_equipment(args.eqpt_filename)
  File "/projects/github/testing/oopt-gnpy/gnpy/core/equipment.py", line 194, in load_equipment
    json_data = load_json(filename)
  File "/projects/github/testing/oopt-gnpy/gnpy/core/utils.py", line 20, in load_json
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'eqpt_file'
`

**NOTE: "eqpt_file" seems to be a parameter description, but this is not clear. Replacing it by eqpt_config.json in examples is successful.
`
python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2_services.json eqpt_config.json -o output_file.json
[Path_request 0
	source:       trx Lorient_KMA
	destination:  trx Vannes_KBE
	trx type:     Voyager_16QAM
	baud_rate:     32000000000.0
	spacing:      50000000000.0
	power:        0.0012589254117941673
, Path_request 1
	source:       trx Brest_KLA
	destination:  trx Vannes_KBE
	trx type:     Voyager_16QAM
	baud_rate:     32000000000.0
...
`

**Comment by dutc** [comment]
Fixed in version 1.0.
