### ISSUE TITLE
Lunching develop branch from binder

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#106]
throwing Error message:
"cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall"

**Note: The use of binder is nowhere described in our readme and it is not clear why binder is needed at all. It looks like it creates more hassle than needed and gnpy is not really maintained to run in that environment. Suggest to remove it for now and focus on a good description based on shell commands**

**Comment by ojnas** [comment]
Seems to be related to this issue with pip version 10 (Ubuntu still has pip version 9):

https://github.com/pypa/pip/issues/4805

**Comment by dutc** [comment]
Binder removed for version 1.0
