### ISSUE TITLE
venv and anaconda

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#107]
Current Readme says:
"It is recommended that you use a virtual environment when installing from the repo. In Python 3, you can use the venv module.

    Note: Alternatively, we recommend the use of the Anaconda Python distribution (https://www.anaconda.com/download) which comes with many scientific computing dependencies pre-installed."

clearly gnpy does not have to describe how to use them, but if there are particular needs to make the code run smoothly in those environments it should be described. 

To run transmission_main_example.py in SPYDER
1. --> python --> PYTHONPATH manager (Add path)
<mypath>/oopt-gnpy

2. --> python --> Preferences --> Run
Default working directory is:
"the following directory: <mypath>/oopt

After that open "transmission_main_example_py" in the editor pane and run by either clicking on the green triangle "run".

alternatively if you want to use the Python console on the bottom right
`
cd <mypath>/OOPT-gnpy/examples
%run transmission_main_example.py
`

**Comment by dutc** [comment]
Fixed in version 1.0.
