### ISSUE TITLE
ModuleNotFoundError: No module named 'examples'

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#111]
I get an error when running transmission_main_example.py:

File "/path/to/gnpy/core/request.py", line 22, in <module>
ModuleNotFoundError: No module named 'examples'

This happens because request.py imports from convert_service_sheet.py in the examples folder (which is not a package). I can get around it by setting PYTHONPATH but I don't think that should be necessary. It is also possible to fix by moving convert_service_sheet.py from the examples folder to the gnpy/core folder and changing from examples.convert_service_sheet to gnpy.core.convert_service_sheet on line 22 in request.py.

**Comment by ojnas** [comment]
This also means that installing using pip does not really "make the library available" as it says in the README.rst since one of the gnpy core modules depends on a module in the examples folder and this folder is not installed when using pip.

**Comment by ggrammel** [comment]
Jonas,

Thanks for the hint. Will work on that for the next release update.

Gert

**Comment by dutc** [comment]
Fixed in version 1.0.
