### ISSUE TITLE
Information about transmission_main_example.py in README is not up-to-date

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#112]
The following description in README is not up-to-date:

> The transmission_main_example.py script propagates a specrum of 96 channels at 32 Gbaud, 50 GHz spacing and 0 dBm/channel. These are not yet parametrized but can be modified directly in the script (via the SpectralInformation tuple) to accomodate any baud rate, spacing, power or channel count demand.

1. The script currently propagates 76 channels, not 96.

2. It is not clear how to modify spectrum parameters directly in the script. The SpectralInformation class is not used directly in the script (even though it is imported). The parameters can however be modified in the eqpt_config.json file.

**Comment by jeanluc-auge** [comment]
Configuration of the spectrum information is described afterwards in the README. 
The section you are refering to was not updated, sorry, but it is now possible to parametrize the spectrum in the 
      examples/eqpt_config.json libray
so there is no need to get into the code. See :
```json
      "SI":[{
            "f_min": 191.3e12,
            "baud_rate": 32e9,
            "f_max":195.1e12,
            "spacing": 50e9,
            "power_dbm": 0,
            "power_range_db": [0,0,0.5],
            "roll_off": 0.15,
            "OSNR": 11,
            "bit_rate":100e9
            }]
```

**Comment by dutc** [comment]
@ojnas Thank you for this report and for your work going through our code. 

We will make sure to update the README before our v1.0 release at the TIP Summit in London.

**Comment by dutc** [comment]
Fixed in version 1.0.

**Comment by ojnas** [comment]
This has not been totally fixed. The text about 96 channels is still there in the README while the script still propagates 76 channels by default.

**Comment by dutc** [comment]
The reference to 96 channels should be removed in the code and the README for the tagged v1.0 release.
