### ISSUE TITLE
roll_off parameter is not used?

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#114]
As far as I can see, the roll_off parameter in SpectralInformation is not used by any code. Is there a reason for keeping it in there? Are there plans to use it in the future (e.g. in a new fiber class computing the GN-model using numerical integration instead of the analytic formula used in the current fiber class in elements.py)?

**Comment by dutc** [comment]
Yes, the `roll_off` parameter is included for future use. 

We do not have immediate plans to implement a new fiber class as you have described, but that is one possibility that we could consider. If this particular use-case is relevant to you, I would encourage you to join our Tuesday Coder's Call (e-mail myself or the chairs for an invite or find details on the TIP Workplace.)

**Comment by dutc** [comment]
@aleFerrari can you also comment on this?

**Comment by ojnas** [comment]
@aleFerrari, as I understand, all published experimental validations used the `phase-1` code (e.g. the JLT paper "Multi-Vendor Experimental Validation of an Open Source QoT Estimator for Optical Networks"). Were the validations based on the double integral or the analytical formula?

**Comment by ojnas** [comment]
@aleFerrari, ok, thanks.

Out of curiosity, why will `roll_off` be needed for Raman? I had a quick look at the current code in oopt-raman and I could not see it being used for calculation. Is it because you will have to use the GN-model based on double integration when Raman is included?

**Comment by aleFerrari** [comment]
@ojnas , correct. In presence of stimulated Raman scattering, the implementation is based on the integrals and it is slower than the analytical formula.
