### ISSUE TITLE
Class Edfa - some minor issues

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#122]
Some things that look strange in the code in `Class Edfa` but does not impact any result:

- In the `propagate` function there is an assignment `i = 0` but this parameter is not used anywhere in the function.

- In the for loop in the same `propagate` function there is an assignment to another variable that is not used: `bw = carrier.baud_rate`.

- In the `_gain_profile` function there is the calculation `tot_in_power_db = lin2db(sum(pin*1e3))` but the same calculation is done in `interpol_params` and assigned to `self.pin_db`. Why not use this?

- The assignment `self.effective_gain = self.operational.gain_target` is done both in `__init__` and in `interpol_params` which seems redundant.

**Comment by dutc** [comment]
Could you submit a pull request with these changes?

Some of them have been addressed with the pre-1.0 release cleanup, but I would like to integrate these comments into a pull requests so that you can get credit for your contribution.

**Comment by dutc** [comment]
Should be resolved with #125
