### ISSUE TITLE
problem with unicode encoding in Windows

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#140]
When I run the following example from the README using Anaconda Python in Windows,

`python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2_services.json eqpt_config.json -o output_file.json`

I get an error message as the script is writing results to a csv file:

`UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 145: character maps to <undefined>`

This is related to #139 (using "→" in fiber element uids) and that python is opening files using the current locale encoding by default, which is CP-1252 and not UTF-8 on my Windows computer. It can be fixed by specifying the encoding when opening the file for writing:

`with open(fnamecsv, "w", encoding="utf-8") as fcsv:`

**Comment by dutc** [comment]
**Great catch!**

We should be explicit about UTF-8 in all of our reading/writing steps.

I'll submit a PR next week with this applied to the entire code base.

**Comment by dutc** [comment]
Should be fixed with #142
