### ISSUE TITLE
examples folder structure

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#146]
There is currently a lot of files in the examples folder which may be confusing to new users. Would it make sense to structure it by adding a couple of sub-folders? For example one folder `/network_topology` for all example topology files and one folder `/equipment_configuration` for all equipment configuration files. Then have only the scripts in either a separate folder or directly under the examples folder.

**Comment by dutc** [comment]
We discussed improving the folder structure at the TIP summit last month.

This is one item on our TO DO list prior to our next major release.
