### ISSUE TITLE
power sweep and default power_range_db

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#147]
I don't know if the following is a bug or intended behavior but to me it's slightly confusing. In the transmission main example there is this code:
```
power_range = list(arange(*equipment['SI']['default'].power_range_db))
        last = equipment['SI']['default'].power_range_db[-2]
        if len(power_range) == 0 : #bad input that will lead to no simulation
            power_range = [0] #better than an error message
        else:
            power_range.append(last)
```
In the default `eqpt_config.json` there is `"power_range_db": [0,0,0.5]`. With this input `power_range` becomes an empty list. It is confusing to have the default input being referred to as "bad input" in the code. Also, setting ` power_range = [0]` in this case may lead to unexpected behavior. For example, if a user inputs `"power_range_db": [1,1,0.5]` it may be expected that `power_range` becomes 1 and not 0.

**Comment by ojnas** [comment]
Also, the use of `numpy.arange` may have unexpected results because of floating point error. For example:
```
>>> arange(1, 1.1, 0.1)
array([1. , 1.1])
```
In this case, since the last value is appended with `power_range.append(last)`, the value 1.1 will be included twice.

**Comment by dutc** [comment]
We'll look into this this week.

**Comment by jeanluc-auge** [comment]
basically tjhe arange function was not doing what I needed, so I tried to modify it.
Knowing that the result of the power range is providing the power excursion around the power_dbm setting (the parameter in the line just before), feel free to propose an enhancement.
Thanks

**Comment by ojnas** [comment]
I would propose using `numpy.linspace` instead. I will submit a PR and then you can check if it does what you want.

**Comment by dutc** [comment]
In general, I think using `numpy.arange` is better than using `numpy.linspace`.

I think these values should be specified as open-closed intervals `[start, stop)` which is consistent with `numpy.arange`, `range`, and slice notation.

Currently, we use the default `json.JSONDecoder` when we call `json.loads`. This comes with a set of assumptions that are causing the above example to break. I think we can start adding some sophistication to our decoding. As a first step, we can use `decimal.Decimal` to preserve user intention and avoid issues with imprecise encoding of real numbers with IEEE-754 binary fp. It's likely that we may have other floating point decoding issues that this can help address, and we can also use this as an opportunity to reorganize some complexity into the decoding/parsing logic.

I think the right answer looks something like:

```python
from json import loads
from decimal import Decimal
from numpy import arange

raw_input = '''
[
    { "power_range": {"start": 1, "stop": 1.1, "step": 0.1} },
    { "power_range": {"start": 1, "stop": 1.5, "step": 0.1} },
    { "power_range": {"start": 1, "stop": 2} }
]
'''

# optionally ...
def object_hook(d):
    if not set(d) - {'start', 'stop', 'step'}: # handle ranges
         return arange(**{k: d[k] for k in ['start', 'stop', 'step'] if k in d})
    return d

loads(raw_input, object_hook=object_hook, parse_float=Decimal)
```

**Comment by ojnas** [comment]
> I think these values should be specified as open-closed intervals [start, stop) which is consistent with numpy.arange, range, and slice notation.

Do you mean the values in the equipment configuration file? Currently power_range in `eqpt_config.json` is specified as a closed interval [start, stop]. That's why the `power_range.append(last)` is needed when using `arange`. Anyway, I don't have a strong opinion on closed vs. half-open.

The numpy documentation itself recommends against using `arange`:
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html

> When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use `linspace` for these cases.

Using `decimal.Decimal` seems to solve it for the specific example I mentioned but I don't have any experience with it so I don't know how general the solution is.

**Comment by ggrammel** [comment]
Tried to figure out how to test, but couldn't really find a way to generate (and test) the issue. Code in transmission_main_example.py has been updated though. IOW: what was the solution of this? It looks like a documentation covering "Using decimal.Decimal seems to solve it for the specific example" is required

**Comment by ojnas** [comment]
@ggrammel One way to test the issue is to set `power_range_db` in `eqpt_config.json` as follows;

`"power_range_db": [1,1.1,0.1],`

Then run transmission_main_example.py and compare the output using the master and the develop branch (with master it will propagate with 1.1 dBm twice).

The currently implemented solution is not using decimal but to use `numpy.linspace` instead of `numpy.arange`.

**Comment by dutc** [comment]
I tested this with the following change to `power_range_db` in `eqpt_config.json`:

```
      "SI":[{
            "f_min": 191.3e12,
            "baud_rate": 32e9,
            "f_max":195.1e12,
            "spacing": 50e9,
            "power_dbm": 0,
            "power_range_db": [1,1.1,0.1],
            "roll_off": 0.15,
            "tx_osnr": 40,
            "sys_margins": 0
            }],
```

I ran:
`$ python transmission_main_example.py CORONET_Global_Topology.json | grep 'Propagating with input power'`

Output was expected (only propagates 1.1 dBm once):
```
Propagating with input power = 1.00dBm :
Propagating with input power = 1.10dBm :
```
