### ISSUE TITLE
path_requests_run.py error

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#149]
Running `path_requests_run.py` without arguments results in an error:

`could not find tsp : vendorA_trx-type1 with mode: PS_SP64_2 in eqpt library`

The default service (and network topology) file, meshTopologyExampleV2.xls, includes a trx mode, PS_SP64_2, which does not exist in eqpt_config.json.

**Comment by EstherLerouzic** [comment]
hello,
thanks for noticing this, I will correct this.
regards
Esther

**Comment by EstherLerouzic** [comment]
This bug is corrected in PR #154.
Regards

Esther

**Comment by EstherLerouzic** [comment]
I have propose a small PR dedicated to the example file

**Comment by dutc** [comment]
Fixed in #161
