### ISSUE TITLE
channel spacing in path_requests_run.py

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#150]
In `path_requests_run.py` the spacing is first set based on input from the service file:

`params['spacing'] = req['path-constraints']['te-bandwidth']['spacing']`

But then the spacing is overwritten by the `automatic_spacing` function called by `trx_mode_params` so that user input does not matter. Is this intended behavior?

**Comment by EstherLerouzic** [comment]
Dear Jonas,
I am currently working on a new feature where this is already corrected. I should be finished within a week and will propose the code through a pull request.
regards
Esther

**Comment by EstherLerouzic** [comment]
This bug is corrected in PR #154 
regards
Esther
