### ISSUE TITLE
synchronization vs. synchronisation

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#152]
After merging the latest "path disjunction" feature, running the `path_requests_run.py` example:
`python path_requests_run.py meshTopologyExampleV2.json meshTopologyExampleV2_services.json`
results in a new error:
```
Traceback (most recent call last):
  File "path_requests_run.py", line 268, in <module>
    dsjn = disjunctions_from_json(data)
  File "path_requests_run.py", line 100, in disjunctions_from_json
    for snc in json_data['synchronization']:
KeyError: 'synchronization'
```
This seems to be related to different spellings, synchronization vs. synchronisation, in different parts of the code.

**Comment by EstherLerouzic** [comment]
Hello
I corrected the CI data files but forgot the json example on the example folder.
Tests are only done on the tests/data files, that is why the CI is passing.
I would suggest to add tests on the examples files in the forder.

**Comment by dutc** [comment]
@EstherLerouzic I agree with adding tests to run through the code in the examples folder. I'll start looking into this.
