### ISSUE TITLE
error running path_requests_run.py with meshTopologyToy.xls

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#158]
Running `path_requests_run.py` with the `meshTopologyToy.xls` example:
`python path_requests_run.py meshTopologyToy.xls meshTopologyToy.xls`

results in error:
```
ValueError:
Requested channel number is not consistent with frequency range:
191.35 THz, 196.1 THz and baud rate: 66.0 GHz
min recommanded spacing is 75000000000.0
max recommanded nb of channels is 63
Computation stopped.
```
I guess this is as it should be since the requested number of channels (64) is higher than the max recommended (63) but do you think it makes sense to include an example that results in an error?

**Comment by dutc** [comment]
Fixed in #161
