### ISSUE TITLE
explicit route with wrong node uid

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#160]
When running `path_requests_run.py` with a service file that includes explicit route constraints, the function `correct_route_list` replaces wrong node uid with the first node uid that partially matches the input. This could be (and often is) a transponder node uid which results in the computed path going through the same ROADM twice. I guess this is not intended behavior. The following comment in `correct_route_list` also indicates that the intention is to only replace wrong node uid with a ROADM node uid:
`# replace possibly wrong name with a formated roadm name`
Some extra check is probably needed in this case.

**Comment by ojnas** [comment]
I was going to propose a PR for this but then I looked at PR #154 and saw that you have probably already fixed it.
(In general I think it would be preferable if fixes like this were separated out in smaller PRs so that they could be reviewed and merged faster.)

**Comment by EstherLerouzic** [comment]
Thanks for checking !
I ll follow your suggestion for next corrections
