### ISSUE TITLE
First usage tips

### ISSUE THREAD

**Issue by MiquelGA** [Telecominfraproject/oopt-gnpy#172]
I hope this is the proper place for these comments:
README
- Stating that by doing "transmission_main_example.py -h" instructions appear would be useful.
- It is not intuitive "between two transceivers selected by the user". An additional sentence with an example would be useful.
I could address these two and few commented in #129 (and few typos) but I have no permission.

Additionally,
- Are those "N channels =  76" of the "transmission_main_example" configurable?
- In the propagation "between trx Albuquerque and trx Atlanta", to which channel do these values OSNR ASE (1nm): 17.45, OSNR ASE (signal bw): 13.37 and SNR total (signal bw): 11.07 belong to?
Thanks!

**Comment by ojnas** [comment]
I agree that the instructions in the README could be improved.

The main configuration file is eqpt_config.json in the examples folder. For example, the number of channels propagated in the "transmission_main_example" can be configured by changing f_min and f_max under SI (Spectral Information).

I think the reported OSNR values are averages over all channels (look at `class Transceiver` in `elements.py`).

**Comment by dutc** [comment]
@MiquelGA thanks for your feedback. Could you submit a PR with the code change to fix the output error in transmission_main_example.py?

**Comment by dutc** [comment]
These were resolved in #175
