### ISSUE TITLE
transmision_main_example.py crashes for some source-destination node combinations

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#176]
Separating this from #130 (which was closed) and reopening since the issue is still present in both develop and master branches:

When running transmission_main_example.py and providing the first node uid in the input json topology file as source and incorrectly specifying the destination, e.g. like this

`python transmission_main_example.py CORONET_Global_Topology.json "trx Abilene" "trx Allbany"`

the program crashes since the destination is replaced with the same node as the source. The program also crashes if the user provides the same correct uid as both source and destination, e.g. like this:

`python transmission_main_example.py CORONET_Global_Topology.json "trx Abilene" "trx Abilene"`

A fix is waiting in PR #144

**Comment by dutc** [comment]
Sorry, this has gotten stalled with our Q1/Q2 2019 milestone planning. I'll look to clear this and the other outstanding PR in the next few days.

**Comment by ggrammel** [comment]
doesn't crash, but behaviour looks strange.

Typo: "souce code" vs. "source code"
Why is trx Abilene', replaced with trx Albuquerque ??? I would think that if the stert/end points are incorrect, the code should end with an error message. Otherwise users are tempted to simply take the figures without checking whether the calculation is effectively based on the input made. 
Suggest to create an error message.

To reproduce:
running ```python transmission_main_example.py CORONET_Global_Topology.json "trx Abilene" "trx Allbany"``` (note typo in Albany) creates this output:
```
invalid souce node specified, did you mean:                  
[]?                  
'trx Abilene', replaced with trx Albuquerque
invalid destination node specified, did you mean:                
[]?                
'trx Allbany', replaced with trx Atlanta
N channels =  76
Power mode is set to True
=> it can be modified in eqpt_config.json - Spans

There are 33 fiber spans over 2945191m between trx Albuquerque and trx Atlanta
```

however when running ```python transmission_main_example.py CORONET_Global_Topology.json "trx Abilene" "trx Albany"``` (Note: Albany is correct) this output is created:
```
invalid souce node specified, did you mean:                  
[]?                  
'trx Abilene', replaced with trx Albuquerque
invalid destination node specified, did you mean:                
[]?                
'trx Albany', replaced with trx Atlanta
N channels =  76
Power mode is set to True
=> it can be modified in eqpt_config.json - Spans
```

**Comment by ojnas** [comment]
@ggrammel I does look like you are running code from the master branch and not from develop.

**Comment by dutc** [comment]
@ggrammel for the purpose of confirming these bugs, could you provide the output of the following three commands in the environment in which you are running the code?

```shell
$ git rev-parse --abbrev-ref HEAD # what branch am I on?
develop
$ git rev-parse HEAD # what is the latest commit for this branch?
ec20d3981b126fa6ff68b71588bc898b1d6e72c3
$ python -c 'import inspect; import gnpy; print(inspect.getfile(gnpy))' # where is Python loading gnpy from?
/path/to/gnpy/__init__.py
```

**Comment by ggrammel** [comment]
Confirmed!



I accidentially cloned the wrong repo



Gert

**Comment by ggrammel** [comment]
Is this really the intended behaviour?

```
python transmission_main_example.py CORONET_Global_Topology.xls z z

<snip>

(Invalid source node 'z' replaced with trx Zurich)
(Invalid destination node 'z' replaced with trx Abilene)
```
I get that one would like to be tolerant against typos, but this goes a bit too far. 
- My preference is to simply throw an error message if the two Transponders do not exist
- In case the team still want to maintain the auto-correction, there should be an option --strict to ensure consistency when desired
- even in the auto-correction case I would suggest to ensure that at least the initial letter of the location is the same. Resolving 'z' to Zurich looks OK, but resolving the second 'z' to Abilene is a bit much.
