### ISSUE TITLE
update of transmission_main_example.py

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#206]
json_structure_description.rst is a good description of the json structure. However it doesn't describe the advanced_config_from_json option. As this structure is a little complex a description would help.

Editorial:
"Description JSON file location is in transmission_main_example.py folder:"
it probably means:
"The Description JSON file shall be in the same folder as transmission_main_example.py:"

**Comment by EstherLerouzic** [comment]
Some updates have been done  in PR #213 
[](https://github.com/Telecominfraproject/oopt-gnpy/pull/213/commits/f21827395bf47a8fc635a1b4c9a262e6501bdf96)

**Comment by dutc** [comment]
Merged with PR #213
