### ISSUE TITLE
README.rst misleading

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#210]
README.rst contains the following sentences:

> The transmission_main_example.py script propagates a spectrum of channels at 32 Gbaud, 50 GHz spacing and 0 dBm/channel. These are not yet parametrized but can be modified directly in the script (via the SpectralInformation structure) to accommodate any baud rate, spacing, power or channel count demand.

Presumably 'the script' in the second sentence refers back to the 'transmission_main_example.py script' in the first sentence. However, the SpectralInformation structure is not defined there but imported from gnpy.core.info

It should be clearer where to define the channels

**Comment by dutc** [comment]
Thanks for this!

Could you consolidate this with #205 and submit a PR with all of the README changes together?

**Comment by ggrammel** [comment]
I am puzzled.
#205 has already been addressed in PR #207 
what is the point to pull it forward into #210 ?

**Comment by dutc** [comment]
Sorry, I meant to consolidate with #206 or other README items if possible.

**Comment by ggrammel** [comment]
Wondering if it is really helpful to merge #206 which is is about the file json_structure_description.rst with #210 that deals with README.rst. What is the issue you would like to address by a merge?

**Comment by EstherLerouzic** [comment]
README updated in #216
