### ISSUE TITLE
Access to the "tip" account at PyPI

### ISSUE THREAD

**Issue by jktjkt** [Telecominfraproject/oopt-gnpy#254]
Someone, perhaps @dutc in #37 , created the[`gnpy` package at PyPI](https://pypi.org/project/gnpy/). There's an [account called "tip"](https://pypi.org/user/tip/) which owns that package.

Can you please help me get access there? My account is called `jktjkt`.

Cc: @diegolaunch

**Comment by jktjkt** [comment]
The repo owner appears to be James, according to the meta information available via web. Given that he said that he no longer can use his `@telecominfraproject.com` mail address, I've filed a request upstream at pypa/warehouse#6049 . Looking at other tickets there, this is a long process.

Once I recover access, I'll ask more people (co-chairs seem to be good candidates) to create accounts there and to make them co-maintainers.

**Comment by ggrammel** [comment]
any progress on that? we should target a solution prior to OFC2020. the package at pypy is pretty old and should be updated.

**Comment by jktjkt** [comment]
Both me and Esther now have access to PyPI.

**Comment by ojnas** [comment]
So will you update the version in PyPI?

**Comment by jktjkt** [comment]
> So will you update the version in PyPI?

Yes, but I would like to automate this via the new CI system instead of pushing it manually.
