### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#269]
I suggest to update some packages to improve the project security:

urllib3 (high severity) : Remediation Upgrade urllib3 to version 1.24.2 or later. For example:
urllib3>=1.24.2
Jinja2 (high severity): Remediation Upgrade Jinja2 to version 2.10.1 or later. For example:
Jinja2>=2.10.1
pyyaml (high severity) Remediation Upgrade pyyaml to version 4.2b1 or later. For example:
pyyaml>=4.2b1
requests (moderate severity) Remediation Upgrade requests to version 2.20.0 or later. For example:
requests>=2.20.0

**Comment by EstherLerouzic** [comment]
I think this issue can be closed

**Comment by jktjkt** [comment]
It looks that GitHub only closes issues once the commits land in the "default branch", which is `master` for us. Thanks for noticing!
