### ISSUE TITLE
add_drop_osnr impact with no ROADMs

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#274]
The parameter `add_drop_osnr` is specified in the Roadm section of eqpt_config.json and represents noise added by amplifiers within the add/drop block of ROADMs. Currently this noise is added to the signal whether the network json includes any ROADMs or not, which does not make sense to me. For example, there is no ROADM in the default edfa_example_network.json but changing the value of `add_drop_osnr` still impacts the result.

**Comment by ggrammel** [comment]
step-1: Note there is no ROADM in the default network file edfa_example_network.json

python transmission_main_example
<snip>
Transmission result for input power = 0.00dBm :
Transceiver Site_B
  OSNR ASE (0.1nm, dB):      32.03
  OSNR ASE (signal bw, dB):  27.95
  SNR total (signal bw, dB): 26.27
  SNR total (0.1nm, dB): 30.35

Step-2: editing eqpt_config.json changing ROADM parameter "add_drop_osnr" from 38 to 100.

python transmission_main_example.py 
<snip>
Transmission result for input power = 0.00dBm :
Transceiver Site_B
  OSNR ASE (0.1nm, dB):      33.30
  OSNR ASE (signal bw, dB):  29.21
  SNR total (signal bw, dB): 27.09
  SNR total (0.1nm, dB): 31.17

Summary:
If an equipment type is not present in the network description file, its parameters shall not alter the result of that network simulation.

**Comment by jktjkt** [comment]
I agree with this (and I vaguely remember that Esther mentioned some reason for this behavior in some Tuesday call?). I would like to change this during the upcoming work on YANGification of the input schemas, along with refactoring of the `SpectrumInformation`.

**Comment by jktjkt** [comment]
Fixed via 0b965d931c81c9661023ae2aa64727e8ba95d94e.
