### ISSUE TITLE
How do we handle provisioning for the network?

### ISSUE THREAD

**Issue by dutc** [Telecominfraproject/oopt-gnpy#31]
- How do we handle "provisioning"/"design" of the network?
- How do we encode parameters vs measured/operational information for network elements?

**Comment by jeanluc-auge** [comment]
for the design of the network, I would propose to have a specific module (meaning it can be bypassed) working on json file:
input = json file with only fibers and transceivers (and ROADM when we have them)
output = new json file adding amplifiers along with provisonning parameters (gain and tilt settings)
This design module can be bypassed if the json file already includes amplifiers (like the edfa_example_network.json). => there is minimal change to the code and the work can be separated.
The design should be performed based on a local opimization, for example:
http://ieeexplore.ieee.org/document/6533111/
The LOGON strategy for low-complexity control plane implementation in new-generation flexible networks
1-calculate the right power level based on span loss and fiber non linearity and following edfa NF
2-chosing the right amplifier in the portfolio of available types that answers the power and gain requirements calculated in step 1
3-in case several amplifier types are possible, chose the one that provides the best NF (i.e. operates at its closest max gain)

Once this very important module it doesn't prevent further optimizations in the main code if needed. But it provides a core starting point based on solid ground with a working solution (if not fully optimum).
