### ISSUE TITLE
topology for demo at TIP Summit

### ISSUE THREAD

**Issue by jktjkt** [Telecominfraproject/oopt-gnpy#315]
The actual demo topology is going to be more complex, but here's a minimal example:
```
                     --> to other Line Degrees in AMS
                    /
                   /
   -----> EDFA +22 ------> EDFA +22 ------> fiber span ------> EDFA +27 ------> EDFA +27 ------>
  /                                                                                             \
TRX  [Add/Drop AMS]    [Line Degree AMS1]                 [Line Degree BER1]   [Add/Drop BER]   TRX
  \                                                                                             /
   <----- EDFA +27 <------ EDFA +27 <------ fiber span <------ EDFA +22 <------ EDFA +22 <------
                   \
                    \
		     <-- from other Line Degrees in AMS
```
The problem is that our ROADMs are "asymmetric". Here's how the EDFA sequence looks like for various LINE vs. local Add/Drop paths:
- LINE -> Express -> LINE: **+27dB** (within a line degree node), then **+22dB** (within another line degree node)
- LINE -> Express -> Drop: **+27dB** (within a line degree node) then **+27dB** (within an add/drop)
- Add -> Express -> LINE: **+22dB** (within an add/drop) then **+22dB** (within a line degree node)

I can create such a topology (the easiest option is using no `Roadm` constructs and just describing the network via `Edfa` and `Fused` nodes), but then `spectrum_assignment` complains because it cannot find any OMS section.

No problem, let's just insert a dummy `Roadm` node to the topo, like in this picture:
```
                              <--> to & from other Line Degrees in AMS
		             /
                            /
                           /
   -----> EDFA +22 \      /   ------> EDFA +22 ---->                    ----> EDFA +27 ---->         -->  EDFA +27 --->
  /                 \    |   /                      \                  /                    \       /                  \
TRX  [Add/Drop AMS]  |---O---  [Line Degree AMS1]    |-------O--------|  [Line Degree BER1]  ---*---  [Add/Drop BER]   TRX
  \                 /    |   \                      /        |         \                    /   |   \                  /
   <----- EDFA +27 /     |    <------ EDFA +27 <----     fiber span     <---- EDFA +22 <----    |    <-- EDFA +22  <---
                         |                                 (node)                               |
                         |                                                                      |
                         ^-- fake "ROADM node"                           another "fake ROADM" --^
```
It turns out that `path_request_run` is not happy with this topology either because `find_reverse_path` correctly recognizes this as a unidirectional topology and refuses to continue...

**Comment by ojnas** [comment]
> The problem is that our ROADMs are "asymmetric". Here's how the EDFA sequence looks like for various LINE vs. local Add/Drop paths:

I think this is the normal way of building a ROADM. The limitation of the current ROADM model in gnpy was pointed out some time ago, see #117.

That said, I don't understand why you can't create "connections" in the topology for both directions (all "connections" in the topology json are unidirectional) through your "dummy" ROADM. Anyway, the ROADM model does not include EDFAs so you always have to model the EDFAs as separate nodes. I think your "dummy" ROADM is actually how the the model is supposed to be used in gnpy.

**Comment by jktjkt** [comment]
Thanks for looking into this. I indeed want to create unidirectional connections, and they work well with `transmission_main_example`. They do not work over `path_request_run` because that code performs forward **and** backward propagation in one go, and assumes that the path is fully bidirectional. In this topology, the path contains unidirectional links. I can code around that, but it's going to be ugly and topology-specific.

**Comment by ojnas** [comment]
> In this topology, the path contains unidirectional links.

What I was trying to say is that links (somewhat confusingly called "connections") in the topology json are always unidirectional. For bidirectional paths you need to have links ("connections") in both directions in the topology. Maybe `path_request_run` should be modified to handle unidirectional paths but I think that is a separate issue from how you specify the topology.

**Comment by jktjkt** [comment]
Let's talk about this during today's coders call. The [code that I'm using is this one](https://github.com/jktjkt/oopt-gnpy/commit/9d662d103935d6d823413a09dc182c27d6508f15), and here's an example of the topology of one "full ROADM node" (two degress, one Add/Drop SRG):
![1346_001](https://user-images.githubusercontent.com/2631925/67282530-83495f00-f4c1-11e9-9b5e-c0f529da953b.jpg)
The code is instrumented to provide extra debugging about the OMS sections that are produced, here's the output:
```
 trx-Amsterdam: Transceiver (OMS n/a)
 att-trx-Amsterdam: Fused OMS 1
        roadm-Amsterdam - roadm-Amsterdam
 roadm-Amsterdam-AD-add: Edfa OMS 1
        roadm-Amsterdam - roadm-Amsterdam
 roadm-Amsterdam: Roadm (OMS n/a)
 roadm-Amsterdam-L1-booster: Edfa OMS 0
        roadm-Amsterdam - roadm-Bremen
 fiber-Amsterdam-Bremen: Fiber OMS 3
        roadm-Bremen - roadm-Bremen
 roadm-Bremen-L1-preamp: Edfa OMS 3
        roadm-Bremen - roadm-Bremen
 roadm-Bremen: Roadm (OMS n/a)
 att-roadm-Bremen-roadm-Bremen-AD-drop: Fused OMS 4
        roadm-Bremen - roadm-Bremen
 roadm-Bremen-AD-drop: Edfa OMS 4
        roadm-Bremen - roadm-Bremen
 att-trx-Bremen: Fused OMS 4
        roadm-Bremen - roadm-Bremen
 trx-Bremen: Transceiver (OMS n/a)
[OMS 3
        roadm-Bremen - roadm-Bremen

, None, OMS 1
        roadm-Amsterdam - roadm-Amsterdam

]
CRITICAL:gnpy.core.request:Error while handling reversed path trx-Bremen to trx-Amsterdam: can not handle unidir topology. TO DO.
```
I am afraid that my topology confuses that part of the code which maps elements to OMS sections. I think that this is due to mixing bidirectional links and unidirectional links. For example, the code believes that there's an OMS between `roadm-Amsterdam` and `roadm-Amsetrdam`, goinv via `roadm-Amsterdam-AD-drop`, `att-trx-Amsterdam`, `roadm-Amsterdam-AD-add`, `roadm-Amsterdam`.

**Comment by EstherLerouzic** [comment]
My suggestion was to create an N+1xROADM mesh topology to represent the final disaggregated roadm, N being the degree. I attached the proposed topology. It is bidirectional, which solves the issue. I suggest to use the add_dropp_osnr to represent the first amplifier. 
[disagregatedTopoDemov1json.txt](https://github.com/Telecominfraproject/oopt-gnpy/files/3755358/disagregatedTopoDemov1json.txt)
![VirtualBox_ubuntu-gnpy_22_10_2019_13_54_06](https://user-images.githubusercontent.com/8588957/67283240-99f8b180-f4d3-11e9-8802-3027e5884358.png)

**Comment by jktjkt** [comment]
(forgot to close this one)
