### ISSUE TITLE
pytest test case test_compare_nf_models is not comparing nf models

### ISSUE THREAD

**Issue by mfreitas02** [Telecominfraproject/oopt-gnpy#321]
**Describe the bug**
When calling the pytest test case "test_compare_nf_models". It does not compare two different amplifier models. It calls the same model twice and then compares the results that are identical.
Unless I am missing something in my observation, this test case is not really doing anything.

**To Reproduce**
1. Go to line 110 in '\tests\test_amplifier.py'
2. Run debug mode the "test_compare_nf_models" method
3. Verify that similar lines of code are running twice 
4. In every condition (Gain), the two nf values calculated are exactly the same

**Expected behavior**
It should run two different models and the nf calculated values should be close, but not exactly the same unless the gain conditions are Gmin or Gmax.

**Comment by ojnas** [comment]
I think you are correct. It seems that following a refactoring of the Edfa class, the test was "corrected" (commit f462201) with the unintentional result that it does not do anything anymore.

**Comment by ojnas** [comment]
Also note that this means there is currently no test covering the advanced, 3rd order polynomial NF, amplifier model (and I don't think there has been for at least 1.5 years).

**Comment by EstherLerouzic** [comment]
Thanks for pointing this !
I propose a correction here https://github.com/Orange-OpenSource/gnpy/tree/correction_test_amplifier could you please have a look and tell me if this is the test you would expect there ?

**Comment by mfreitas02** [comment]
Thanks Esther!
I checked your changes and I can see that now it is comparing two different nf models as it was expected.
