### ISSUE TITLE
pytest testcase test_ase_noise is calculating the same EDFA NF for all gain conditions

### ISSUE THREAD

**Issue by mfreitas02** [Telecominfraproject/oopt-gnpy#324]
**Describe the bug**
The testcase test_ase_noise is calculating the same NF values for all gain conditions (13, 15, 17, 19, 21, 23, 25, 27). Currently NF is always calculated as 25dB for all gain values. This is due to the current setting of p_spani in pref:
pref = Pref(0, 0, lin2db(len(frequencies)))
By defining p_spani as zero, the EDFA calculated gain becomes zero and consequently 15dB (Gmin) is added to the EDFA NFmax, getting to the nf of 25dB for all test conditions.
In this case, all the OSNRs calculated are kept the same 33dB
I am not sure about the need of having so many gain conditions if they do not impact the results.

**To Reproduce**
1. Go to line 129 in '\tests\test_amplifier.py'
2. Run "test_ase_noise" in debug mode
3. Verify that p_spani is always set to 0
4. When calling "edfa.interpol_params" function, it always calculates nf as 25 dB
Gain(dB) | NF cal.(dB) | Pase(W)    | OSNR(dB)
13           | 25              | 1.804E-06 | 33
15           | 25              | 1.804E-06 | 33
17           | 25              | 1.804E-06 | 33
19           | 25              | 1.804E-06 | 33
21           | 25              | 1.804E-06 | 33
23           | 25              | 1.804E-06 | 33
25           | 25              | 1.804E-06 | 33
27           | 25              | 1.804E-06 | 33

**Expected behavior**
I modified the value of p_spani and the osnr_expected equation to follow the change introduced by p_spani. After that I could see the NF and OSNR variation accordingly. However, this change caused a mismatch with the calculation of OSNR through pout/pase after propagate.
I was wondering if we should let the test the way it is (with fixed NFs), or try to modify it to really vary with the gain conditions.

**Environment:**
 - OS: [e.g. Windows]
 - Python Version [e.g, 3.7]
 - Anaconda Version [e.g. 3.7]

**Additional context**

**Comment by EstherLerouzic** [comment]
I think your suggested change is a good idea. I have tried to adress it here https://github.com/Orange-OpenSource/gnpy/tree/correction_test_amplifier could you please have a look ?
