### ISSUE TITLE
python can't open setup.py

### ISSUE THREAD

**Issue by taymasaad** [Telecominfraproject/oopt-gnpy#338]
when trying to install setup.py of the gnpy. I've got errors.
please help

**Comment by jktjkt** [comment]
Hi @taymasaad, please tell us exactly how you're trying to install GNPy. Are you following a particular tutorial? Which one? Could you please paste the exact error messages (the full output from the terminal)?

**Comment by taymasaad** [comment]
I am using those command to install gnpy:
$ git clone https://github.com/telecominfraproject/gnpy
$ cd gnpy
$ python setup.py install
 from https://pypi.org/project/gnpy/
and this is what I've got 
python: can't open file 'setup.py': [Errno 2] No such file or directory

thanks for help

**Comment by jktjkt** [comment]
Please follow [these instructions that are described in our `README`](https://github.com/Telecominfraproject/oopt-gnpy#how-to-install), and kindly let us know if you hit any problem. Unfortunately, the package at PyPI is a bit outdated.

**Comment by jktjkt** [comment]
Hi there, just FYI, starting from the 2.2 release our PyPI packaging works again. So right now it should be just a matter of running `pip install gnpy` from your Python 3.6+ environment.
