### ISSUE TITLE
What's the meaning of delta_p?

### ISSUE THREAD

**Issue by Tobelightbeam** [Telecominfraproject/oopt-gnpy#360]
After reading the source code, i am confused by delta_p. At the beginning, i thought that delta_p is related to the intial channel power pref_span0. However, in some files I found that the value of a ROADM's target_pch_out_db is directly assigned to its dp. 
In my opinion, target_pch_out_db equals dp only when initial channel power is 0 dBm. Therefore, the meanning of delta_p (dp) confused me a lot. 
Can anyone explain the meanging of dp and the benefits introducing it?
I would be appreciate if someone could help :)

**Comment by ojnas** [comment]
> However, in some files I found that the value of a ROADM's target_pch_out_db is directly assigned to its dp.

Could you clarify this? What files and what code are you referring to?

**Comment by Tobelightbeam** [comment]
> > However, in some files I found that the value of a ROADM's target_pch_out_db is directly assigned to its dp.
> 
> Could you clarify this? What files and what code are you referring to?

I found this in gnpy.core.network, line 254: prev_dp = getattr(roadm.params, 'target_pch_out_db', 0)

By the way, in line 236 and 237,  the value of voa is added to original delta_p for modiication. But since the value of voa is positive which responds to the decling of output power, maybe the value of voa should be substracted from the original dleta_p?

**Comment by ojnas** [comment]
> After reading the source code, i am confused by delta_p. At the beginning, i thought that delta_p is related to the intial channel power pref_span0.

This is correct, the target channel power out from an amplifier is p_span0 + delta_p. Here p_span0 is not really the "initial" channel power but rather the target power for a reference span loss of 20 dB (this 20 dB number is hardcoded in network.py) 

> However, in some files I found that the value of a ROADM's target_pch_out_db is directly assigned to its dp.
> In my opinion, target_pch_out_db equals dp only when initial channel power is 0 dBm. Therefore, the meanning of delta_p (dp) confused me a lot.

I think you are correct and that this is a bug in the code. In most cases this will not impact propagation results since the gain is anyway updated during propagation (see the interpol_params function of the Edfa class in elements.py). But the gain reported by the to_json function of amplifier elements before propagation will be wrong. I'm using this function to show information when hovering over elements in the web UI running at https://gnpy.app/ so thanks for reporting this.

> By the way, in line 236 and 237, the value of voa is added to original delta_p for modiication. But since the value of voa is positive which responds to the decling of output power, maybe the value of voa should be substracted from the original dleta_p?

The gain and power out from the amplifier is increased to compensate for the VOA so I think the code is correct in this case.

**Comment by Tobelightbeam** [comment]
> The gain and power out from the amplifier is increased to compensate for the VOA so I think the code is correct in this case.
So, does the target output power of an amplifier exclude the influence of the VOA at output side? I thought that VOA is part of an amplifier. Therefore, delta_p of an amplifier in my mind was based on the output power after VOA and that might not be right >.< The concept of delta_p is so confused for me that I would rather use gnpy in gain mode rather than in power mode.
I have tried the web UI before and i think it is not a bad idea for beginners like me. Thanks.

**Comment by Tobelightbeam** [comment]
@ojnas 
I got the difference between pref_span0 and initial channel power. It's because pref_span0 is passed to build_network for adjusting elements' parameters. After that, initial channel power is set according to pref_span0 + power_range_db (which is enabled in power mode). Therefore, initial channel power doesn't equal pref_span0 all the time.
Thanks for your help.

**Comment by ojnas** [comment]
Normally an output VOA is an integral part of an amplifier and output power (and net gain) is specified including this VOA. But the out_voa parameter in GNPy models an external VOA (see the propagate function of the Edfa class in elements.py) that can optionally be used to operate an amplifier at optimum gain. You can set it manually in the topology file or it can be set automatically when using autodesign in power mode if the amplifier type explicitly allows it (specified by the out_voa_auto parameter). In most cases e.g. with a variable gain amplifier performing internal optimization, this functionality should be disabled by setting out_voa_auto to false.

I think the distinction between power mode and gain mode in GNPy is a bit misleading. It mainly applies to autodesign and gain mode does not really work well with the autodesign implementation. So the distinction is rather between autodesign or not. Note that if you know exactly the topology you want to simulate and specify all gain values, etc., manually you can simply skip the autodesign step by not calling the build_network function from your main program. But if you want to try out some example topologies, like CORONET, etc., then you need the autodesign and you should probably use power mode.

By the way, would you like to contribute to the code and maybe propose fixes for the bugs you have discovered?

**Comment by Tobelightbeam** [comment]
> By the way, would you like to contribute to the code and maybe propose fixes for the bugs you have discovered?

Yes, I'd like to. Although I am just a beginner for coding, I will try to improve myself. Is there anything I need to do if i want to contribute to the code?

**Comment by ojnas** [comment]
> > By the way, would you like to contribute to the code and maybe propose fixes for the bugs you have discovered?
> 
> Yes, I'd like to. Although I am just a beginner for coding, I will try to improve myself. Is there anything I need to do if i want to contribute to the code?

Great! We're using GerritHub for patches and code review:
https://review.gerrithub.io/p/Telecominfraproject/oopt-gnpy/+/dashboard/main:main

@jktjkt, can you give further instructions (there doesn't seem to be up-to-date information on GitHub)?

**Comment by jktjkt** [comment]
Fixed, thanks, @ojnas.

Re Gerrit instructions, it seems I forgot to reply here when I [fixed that](https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/501489) (f6c2da24cde9278bdbca97ccf1a8d32d15736e14) -- sorry, and thanks for catching that. I hope it's better now.
