### ISSUE TITLE
Should not add_connetor_loss be done when split_fiber is finished?

### ISSUE THREAD

**Issue by Tobelightbeam** [Telecominfraproject/oopt-gnpy#361]
**Is your feature request related to a problem? Please describe.**
In core.network, funtion build_network adds connector loss to fiber before splitting fibers which are too long into new shorter spans. Isn't it better to add connector loss and fiber padding after spliting fibers?

**Comment by ojnas** [comment]
I think you raise a good point. The new fiber spans "inherit" parameters from the original fiber, which I think is ok for the connector loss (or do you think it should be handled differently?). But the way padding is handled in the current implementation looks questionable. I think it could happen that a fiber is split into spans with lower loss than the padding and then proper padding is not applied.

**Comment by Tobelightbeam** [comment]
Thanks. 
After reviewing the code, I have gotten the meanning of "inherit". And I agree your points about padding. I think that spliting fiber first is more intuitive and flexible.
