### ISSUE TITLE
About dp of exgress amplifiers of a ROADM

### ISSUE THREAD

**Issue by Tobelightbeam** [Telecominfraproject/oopt-gnpy#368]
**Describe the bug**
The setting of delta_p for a ampifier is not consistent.

Details:
In gnpy.core.network.py, line 268: 
`gain_target = node_loss + dp - prev_dp + prev_voa`
which says that gain_target is set accroding to node_loss (span loss), prev_dp, prev_voa and dp, in power mode.

In line 271:
`dp = prev_dp - node_loss + gain_target`
which says dp is set according to gain_target, prev_dp and node loss (span loss), in gain mode. But 'prev_voa' is missing. 

Will 'prev_voa' be different when in power mode and gain mode??

**Comment by EstherLerouzic** [comment]
Thanks for pointing this. We will check and come back to you asap.

**Comment by ojnas** [comment]
This does look like a bug to me. The previous out_voa attenuation should be taken into account also in gain mode when calculating power_target used for automatic amplifier selection.

**Comment by Tobelightbeam** [comment]
@EstherLerouzic , @ojnas :
Thanks.

By the way, in the gnpy_transmission_example which using `edfa_example_network.json` by default, the mode of a Transceiver is not used. Instead, values under SI is adopted to set frequency, baud_rate, tx_osnr and so on. Are there any documents telling how to use the format of a transceiver?

**Comment by ojnas** [comment]
@Tobelightbeam, the fix for the prev_voa issue should be straightforward. Do you want to propose a patch on gerrit?

**Comment by Tobelightbeam** [comment]
@ojnas , I'm still a beginner for Git and Coding. So maybe this time I wouldn't propose a patch on gerrit. But I'd like to know the progress of the issue.

**Comment by ojnas** [comment]
@Tobelightbeam, ok, I proposed a fix here:

https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/505131

**Comment by ojnas** [comment]
Just to be clear: the proposed fix has not been merged yet. I think it would be better to keep this issue open until a decision has been made about the patch.

**Comment by jktjkt** [comment]
Fixed, thanks, @ojnas.
