### ISSUE TITLE
update snr considering tx_osnr and add_drop_osnr

### ISSUE THREAD

**Issue by Tobelightbeam** [Telecominfraproject/oopt-gnpy#372]
In request.py, the method `propagate` is used to calculate the change of spectral information along a path.
At the end of a path, the final osnr is calculated considering tx_osnr of the begining transceiver and add_drop_osnr of Roamds.
But as seen in the code, it seems that only one Roadm is taken into account:
`path[-1].update_snr(req.tx_osnr, equipment['Roadm']['default'].add_drop_osnr)`.
Therefore, when there are multiple roamds in a path, the final onsr will not be that correct.

![image](https://user-images.githubusercontent.com/26196100/99218315-1d8aec00-2815-11eb-9f39-19db076f4056.png)

**Comment by Tobelightbeam** [comment]
Since add_drop_osnr may be high (eg. 35dB), the influence may be minimal.

**Comment by EstherLerouzic** [comment]
add_drop_osnr includes add and drop contribution coming from amplifiers that may be used on add drop blocks, and that are not modelled as amplifier elements in the path. ROADM's express path noise contribution is accounted thanks to preamp and booster amplifiers which are modelled as amplifier elements in GNPy. apart from these amps, an express path is not supposed to add any other noise contribution in standard ROADMs. So on a given lightpath, there is only one add and one drop, so the add-drop_osnr contribution should only be accounted once. Hope this clarifies these lines.

**Comment by Tobelightbeam** [comment]
@EstherLerouzic ,thanks for your answer.
But there are still some points remaining unclear. Do those amplifiers which are not modelled as amplifier elements means amplifiers connected to add or drop ports of an Roadm? By contrast, preamp and booster amplifiers denote amplifiers connected to In and Out Port respectivly?

**Comment by jktjkt** [comment]
@Tobelightbeam, that's correct; in GNPy the `Roadm` element refers just to that switching & filtering part of a traditional ROADM node. The in/out amplifiers (preamp/booster) are modeled explicitly via dedicated `Edfa` nodes.

The code that you highlighted also refers to another "irregularity" where we add the transponder's TX OSNR only once after all the propagation is done. The reasons behind that are described in https://github.com/Telecominfraproject/oopt-gnpy/pull/311#issuecomment-538875411 .

Please feel free to reopen if there's anything more that needs our attention.

**Comment by ojnas** [comment]
> Do those amplifiers which are not modelled as amplifier elements means amplifiers connected to add or drop ports of an Roadm?

It's both - the add_drop_osnr models the total contribution from amplifiers in both the add stage of the first ROADM and the drop stage of the last ROADM in the path.
