### ISSUE TITLE
Bug on target_pch_out_db

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#380]
**Describe the bug**
change [fix calculation of gain ...](https://review.gerrithub.io/plugins/gitiles/Telecominfraproject/oopt-gnpy/+/928bc42cb9e3336525e04e4f95640d1e66de5dbd)
seems to introduce an unwanted behaviour on target_pch_out_db: it changes its value.
when using mesh_exemple_topology file with -20dBm target power and 1.5 dBm target input power in fiber, the target_pch_out_db is changed to -21.5dBm, and the resulting gain is thus increased by twice the value of power: +3 dB

This behaviour appears in any case in power mode.

here is an example ( with -20dBm roadm/target_pch_out_db and 1.5 dBm SI/power_dBm) :

Propagating with input power = 1.50 dBm:
Transceiver trx Lannion_CAS
  OSNR ASE (0.1nm, dB):      40.00
  OSNR ASE (signal bw, dB):  35.92
  SNR total (signal bw, dB): 35.92
  SNR total (0.1nm, dB):     40.00
  CD (ps/nm):                0.00
  PMD (ps):                  0.00
Roadm roadm Lannion_CAS
  effective loss (dB):  23.00        -> should be -21.5
  pch out (dBm):        -21.5        -> should be -20
Edfa east edfa in Lannion_CAS to Corlay
  type_variety:           std_medium_gain
  effective gain(dB):     24.00     -> should be 22.5
  (before att_in and before output VOA)
  noise figure (dB):      6.06   (changing accordingly)
  (including att_in)
  pad att_in (dB):        0.00
  Power In (dBm):         -2.69
  Power Out (dBm):        21.32
  Delta_P (dB):           1.0
  target pch (dBm):       2.5
  effective pch (dBm):    2.5
  output VOA (dB):        0.00

**To Reproduce**
1. change power_dBm to 1.5dBm
2. run transmission_main_example on meshTopologyExempleV2.xls gnpy-transmission-example meshTopologyExampleV2.xls -e eqpt_config.json

**Comment by ojnas** [comment]
Confirmed. Fix waiting here:

https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/509329

**Comment by ojnas** [comment]
Fixed by https://github.com/Telecominfraproject/oopt-gnpy/commit/f9dbf7d13265113233774590b510d0fc5c80dbdf
