### ISSUE TITLE
What are the meanings of “con in” and “con out” in the propagation function respectively？

### ISSUE THREAD

**Issue by zodical416** [Telecominfraproject/oopt-gnpy#388]
In the function "propagation", there are two parameters “con in” and “con out” I don't know their meanings. I'd appreciate it if you could tell me！Thanks！

**Comment by jktjkt** [comment]
You're referring to [this function in the test suite](https://github.com/Telecominfraproject/oopt-gnpy/blob/eaccd63/tests/test_propagation.py#L28), right? These are connector losses. Just wondering -- any particular reason why this function caught your interest?

**Comment by zodical416** [comment]
> You're referring to [this function in the test suite](https://github.com/Telecominfraproject/oopt-gnpy/blob/eaccd63/tests/test_propagation.py#L28), right? These are connector losses. Just wondering -- any particular reason why this function caught your interest?

Thanks for your answer! I hope to use this function to calculate the OSNR of the light path, and I find this function can output the OSNR information.

**Comment by shineslsl** [comment]
I'm also working on this project, and I have a problem, sometimes the output OSNR is a positive number but SNR is a negative number. So could you tell me what is the general reason for this? Thanks!

**Comment by ojnas** [comment]
> I'm also working on this project, and I have a problem, sometimes the output OSNR is a positive number but SNR is a negative number. So could you tell me what is the general reason for this? Thanks!

OSNR and (G)SNR are just signal-to-noise ratios and there is nothing fundamental about positive vs. negative (in dB). A negative SNR just means you have more noise than signal power. In GNPy, OSNR only includes contributions from amplifier ASE noise, while (G)SNR also includes NLI (i.e. contributions from nonlinear fiber propagation). If there is a large difference between OSNR and (G)SNR, it means propagation is very nonlinear and you should probably check if your input parameters are reasonable. Also if you have very low (G)SNR (even negative) it means no optical transceiver will be able to decode the signal so you should again check your input parameters.

**Comment by shineslsl** [comment]
> > I'm also working on this project, and I have a problem, sometimes the output OSNR is a positive number but SNR is a negative number. So could you tell me what is the general reason for this? Thanks!
> 
> OSNR and (G)SNR are just signal-to-noise ratios and there is nothing fundamental about positive vs. negative (in dB). A negative SNR just means you have more noise than signal power. In GNPy, OSNR only includes contributions from amplifier ASE noise, while (G)SNR also includes NLI (i.e. contributions from nonlinear fiber propagation). If there is a large difference between OSNR and (G)SNR, it means propagation is very nonlinear and you should probably check if your input parameters are reasonable. Also if you have very low (G)SNR (even negative) it means no optical transceiver will be able to decode the signal so you should again check your input parameters.

Thanks a lot！
