### ISSUE TITLE
.dgt vector not properly read or interpolated

### ISSUE THREAD

**Issue by cgkelly** [Telecominfraproject/oopt-gnpy#397]
I have defined .dgt vectors for the advanced edfa models,  and also assigned non-zero gain tilts.  I expected the gain ripple to translate into OSNR ripple at the output of a path,  but did not see any ripple.

With some help from Esther,  I added some lines to cli-examples.py to attempt to debug this (is there a  better way to get more information about gain/OSNR evolution along a path, for such debugging purposes? )

around line 238,  after 'for elem in path:', added
if (hasattr(elem,'effective_gain')):  
   print(vars(elem))

I used the hasattr to check if the element is an amp, to avoid an excessive data dump.
The result shows that the GNPY used .dgt vector starts with a very similar (but not exact) value to the first one defined in my .dgt vector,  but the remaining values did not vary much, and did not reflect my .dgt vector.

Going through the closed issues,  it appears there was an issue in interpolation when freq. was defined in THz instead of Hz (or vice versa);  my amp models have start/stop freq's in Hz, and so does the SI data in my eqpt_config file,  so it appears this is correct.    Comparison graph attached.

[defined vs GNPY used .dgt vectors.pptx](https://github.com/Telecominfraproject/oopt-gnpy/files/6467011/defined.vs.GNPY.used.dgt.vectors.pptx)

**Comment by ojnas** [comment]
Is it the `interpol_dgt` vector you are looking at? With start/stop freq you are referring to `f_min/f_max` in the advanced amp config file? It sounds like an interpolation issue but it is difficult to say without more info. Would it be possible to share input files for which this happens so that I can try to reproduce the issue?

**Comment by cgkelly** [comment]
Update - this appears to be resolved by removing fmin, fmax from the amplifier.json files.

**Comment by ojnas** [comment]
@cgkelly, removing `f_min` and `f_max` is not really a solution since then it will just use 191.35 THz and 196.1 THz by default (which may or may not match your defined DGT values). There must be some error in how you define these values in the json file. If you could just copy and paste that part of the file here I could maybe identify the issue.

**Comment by cgkelly** [comment]
I had fmin, fmax defined in both the SI section of the  eqpt_config.json file:

"SI": [
    {
      "f_min": 191300000000000,
      "baud_rate": 32000000000,
      "f_max": 196100000000000,


And in the amp .json files:

"nf_fit_coeff": [
    -0.0030742,
    0.0032491,
    -0.10437,
    4.6595
  ],
  "f_min": 191300000000000,
  "f_max": 1961000000000000,

(with the nf ripple, gain ripple, dvt vectors following).

Eliminating the two highlighted entries (per amp json file) solve the problem.  Thus,  it does appear to be related to the old (closed) issue with regard to interpolation problems.

Thanks,
Colin

**Comment by cgkelly** [comment]
Yes, thanks - I realize the limitation of this approach, but I had aligned my .dgt frequencies with the SI grid via matlab.  I should reopen the issue, however,  as it isn’t resolved.

Colin

**Comment by ojnas** [comment]
Looks like `f_max` has one `0` to many in your amp json file. That would explain why the interpolated values look wrong.

**Comment by ojnas** [comment]
@cgkelly, see reply above

**Comment by cgkelly** [comment]
Thanks for the catch...obvious now.

Colin

**Comment by jktjkt** [comment]
I looked into how we could prevent a case like this in future. In the upcoming YANG work, the amplifier's `f_min` and `f_max` are range-limited, so you should hopefully get a helpful error message. Also, the DGT vector will be passed not as a "list of numbers", but rather as an explicit mapping from the frequency to the DGT value at that point -- and the frequencies will be range-checked.

So I think we'll be covered, and this one can be closed.
