### ISSUE TITLE
Auto gain and output eVOA setting

### ISSUE THREAD

**Issue by cgkelly** [Telecominfraproject/oopt-gnpy#409]
I cannot get expected behavior for an advanced EDFA model, for gain and ouput eVOA setting.
In my equip_config.json file, which contains new advanced amp models:
      Amp models:  out_voa_auto set to true
      Span,  power_mode set to true
      
In my topology.json file,  for each instance of the new amps, 
    gain_target set to 0  (which should result in auto-design). 
   delta_p set to null (is this correct?)
   out_voa:  I have set this to null and zero,  and also eliminated this entry; same results.
   
My amplifiers are set below their max. gain/output power, and the eVOA setting appears to be zero, no matter what I try. 
(If I set the power_mode to false,  and gain_target to null, I get the same EDFA gains;  setting the gain_target to 0 does indeed 
result in 0 gain, so the power_mode=true and gain_target=0 does work. 
   
I also tried setting a fixed eVOA value, as there is no easy way of determining the intrinsic amplifier gain and output eVOA setting.  Setting a non-zero eVOA value results in the same intrinsic amplifier gains; the net gain just drops by this extra eVOA loss.  

Expected behavior:  Amplifier gains set to the maximum possible value, and the output eVOA values set as required to achieve the determined output power.    
   
I then tried this with the operator_model_example in the original equip_config.json file, and toggled the out_eVOA_auto field
on and off, and obtained the same results (no change in the amp gains, amps are operating below their max. gain and output power).  The topo file and eqpt_config files using this amp are attached, with .json extension to .txt.
[5span_SRScheck_nopumps.txt](https://github.com/Telecominfraproject/oopt-gnpy/files/6633645/5span_SRScheck_nopumps.txt)
[eqpt_config.txt](https://github.com/Telecominfraproject/oopt-gnpy/files/6633648/eqpt_config.txt)

Note - I'm using Raman spans to obtain SRS tilt).

**Comment by cgkelly** [comment]
Thanks.

I tried it again with gain target = 0,  which should be ignored with power_mode true,  but I did not get any output eVOA attenuation.
However, in the West direction, once I eliminated all the gain target and delta p statements, it worked.

Is there any way to tell what the eVOA settings are,  as I only see the net gains.

Colin

**Comment by ojnas** [comment]
@cgkelly,

>Is there any way to tell what the eVOA settings are,  as I only see the net gains.

The out_voa setting for every amplifier in the path is printed when you run gnpy-transmission-example. In [gnpy.app](https://gnpy.app/) you can also see the setting resulting from auto-design for every amp in the network by hovering over it in the topology graph with the mouse.

**Comment by cgkelly** [comment]
Thanks, Jonas.

For my example 5 span network (using my amps instead of the files I sent you), the app times out.   I’m running directly from a command window,
scripts\gnpy-transmission-example ./example-data/Raman_topo_5.json --sim ./example-data/sim_params.json -e ./example-data/my_eqpt_config.json --show-channels

The output from this (using your modified request.py file) lists the amp input/output power levels,  and the SNRs at the end of the path,  but not the eVOA values.

Colin

**Comment by ojnas** [comment]
@cgkelly,

>For my example 5 span network (using my amps instead of the files I sent you), the app times out.

I see, that's unfortunate. This is related to the idle timeout of the Azure load balancer and there is not much I can do about it. How long does it take to run the script on your computer? Note that you can see out_voa values, etc., resulting from auto-design in the topology graph in the app even before running a simulation (i.e. by clicking "Run simulation" or uploading a services file).

>The output from this (using your modified request.py file) lists the amp input/output power levels,  and the SNRs at the end of the path,  but not the eVOA values.

That is strange, it should be printed. Did you somehow modify cli_examples.py as well because that is where the printing of information about all elements in the path happens?

**Comment by cgkelly** [comment]
Upgraded to release 2.3.1,  and I now see the eVOA settings.  I also see them auto-set if I permit. Some other pecularities with their settings,  but this is a different issue.
