### ISSUE TITLE
Installation problem with gnpy as per instructions on  https://gnpy.readthedocs.io/en/master/install.html#installing-the-python-package

### ISSUE THREAD

**Issue by superpositon** [Telecominfraproject/oopt-gnpy#433]
**Describe the bug**

Conda cannot resolve the command
$ git clone https://github.com/Telecominfraproject/oopt-gnpy 

**Screenshots**
![image](https://user-images.githubusercontent.com/84708199/158627601-5e403a57-d59b-4bbd-80b0-32f57fb0d98a.png)

**Environment:**
 - OS: [ Windows]
 - Python Version [ 3.8.8]
 - Anaconda Version [3]

**Additional context**
Do i need to be a member of TIP, I am a independent enthusiast. Kindly help , thanks in advance. Martin.

**Comment by jktjkt** [comment]
Hello, there are many ways on how to install GNPy. If you're interested just in trying it out, getting the Docker container is probably the easiest option. If you want to install the latest development release, it is required to install [Git](http://git-scm.com/) as well. However, it is also possible to simply install the Python package via invoking `pip install gnpy` (instead of `git clone ...`, `cd ...` and `pip install ...`).

**Comment by superpositon** [comment]
> Hello, there are many ways on how to install GNPy. If you're interested just in trying it out, getting the Docker container is probably the easiest option. If you want to install the latest development release, it is required to install [Git](http://git-scm.com/) as well. However, it is also possible to simply install the Python package via invoking `pip install gnpy` (instead of `git clone ...`, `cd ...` and `pip install ...`).

Thanks alot, I used pip install and have gnpy working . I am currently reading your co-authored paper  'GNPy: an open source application for physical
layer aware open optical networks'. Hope it can get me started on gnpy.  If you are aware of any material out there that can further help, will be glad to help. Cheers. Martin.

**Comment by jktjkt** [comment]
We have some howto videos, see [this discussion](https://github.com/Telecominfraproject/oopt-gnpy/discussions/378#discussioncomment-282301). We're in process of refreshing that information (some command names have changed, etc), but these videos should get you going.
