### ISSUE TITLE
Is it possible to consider  different types of transmitters for a same simulation?

### ISSUE THREAD

**Issue by indayara** [Telecominfraproject/oopt-gnpy#436]
**Is your feature request related to a problem? Please describe.**

Is it possible to create one simulation script applying more than one type of transmitter for a same simulation?
I see that it is possible to create some identical transmitters for a same simulation. 

I would appreciate to develop a simulation script considering a transmission block as:

1- Transmitter working : 32Gbaud/roll off 0.2/Pin =1dBm/ChannelSpacing =37.5GHz/ Channel:33
2 - Transmitter working: 66Gbaud/roll off 0.2/Pin = 1dBm/Channel Spacing=75GHz/Channel:34
3- Transmitter working: 41Gbaud/roll off 0.2/Pin = 1dBm/Channel Spacing=50GHz/Channel:35.5
etc .....

Thanks in advance,
Best regards,
Indayara

**Comment by ojnas** [comment]
Hi Indayara,

this is not supported in the current version but such a feature has been under development for some time and will hopefully be released soon. In the meantime, there is experimental support for this in https://gnpy.app/ that you can play around with (click "define mixed spectrum").
