### ISSUE TITLE
internal: simplify type annotations for `float`

### ISSUE THREAD

**Issue by jktjkt** [Telecominfraproject/oopt-gnpy#450]
As per [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower), the type annotations do not have to say `Union[int | float]`, just a `float` is OK.

**Comment by SamiAlavi** [comment]
Hi @jktjkt, can I work on this?

**Comment by jktjkt** [comment]
@SamiAlavi , yes please, patches are very welcome.
