### ISSUE TITLE
The first amplifier is not getting the target gain defined in the JSON topology file. 

### ISSUE THREAD

**Issue by gupavani** [Telecominfraproject/oopt-gnpy#486]
**Bug description**

I built a simple linear topology for obtaining the GSNR in gain mode. It worked on the 2.7.1.dev12 version of GNPy. But, when I updated GNPY to version 2.8.1.dev2 by cloning the master repository, the first amplifier got a very low gain, although the target gain was set to 15 dB in the JSON topology file. 

**Expected behavior**
The gain of the first amplifier should be equal to the target gain defined in the JSON topology file.

**Comment by EstherLerouzic** [comment]
Thanks for identifying this bug ! I have sumitted to correction
Regards
