### ISSUE TITLE
testing gnpy after fresh install: error running examples

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#55]
2018-04-16: after testing the installation using pip install I realized that timestamps in the local folder gnpy were older than the master (see separate issues)

1) Then I deleted an older gnpy folder and started afresh,  cloning from master.
2) the timestamps of files were actual (as expected)
3) running the first example from Readme --> no success
3) running second example from Readme --> no success

IOW I wasn't able to run the examples from Readme

```
ggrammel-mbp:github ggrammel$ git clone https://github.com/Telecominfraproject/gnpy**
Cloning into 'gnpy'...
remote: Counting objects: 694, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 694 (delta 1), reused 3 (delta 0), pack-reused 685
Receiving objects: 100% (694/694), 349.50 KiB | 501.00 KiB/s, done.
Resolving deltas: 100% (365/365), done.
```
```
ggrammel-mbp:github ggrammel$ cd gnpy
ggrammel-mbp:gnpy ggrammel$ python setup.py install
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating gnpy.egg-info
writing gnpy.egg-info/PKG-INFO
writing dependency_links to gnpy.egg-info/dependency_links.txt
writing requirements to gnpy.egg-info/requires.txt
writing top-level names to gnpy.egg-info/top_level.txt
writing manifest file 'gnpy.egg-info/SOURCES.txt'
reading manifest file 'gnpy.egg-info/SOURCES.txt'
writing manifest file 'gnpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gnpy
copying gnpy/__init__.py -> build/lib/gnpy
creating build/lib/gnpy/core
copying gnpy/core/__init__.py -> build/lib/gnpy/core
copying gnpy/core/elements.py -> build/lib/gnpy/core
copying gnpy/core/execute.py -> build/lib/gnpy/core
copying gnpy/core/info.py -> build/lib/gnpy/core
copying gnpy/core/network.py -> build/lib/gnpy/core
copying gnpy/core/node.py -> build/lib/gnpy/core
copying gnpy/core/units.py -> build/lib/gnpy/core
copying gnpy/core/utils.py -> build/lib/gnpy/core
creating build/bdist.macosx-10.6-intel
creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/gnpy
copying build/lib/gnpy/__init__.py -> build/bdist.macosx-10.6-intel/egg/gnpy
creating build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/__init__.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/elements.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/execute.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/info.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/network.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/node.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/units.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
copying build/lib/gnpy/core/utils.py -> build/bdist.macosx-10.6-intel/egg/gnpy/core
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/elements.py to elements.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/execute.py to execute.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/info.py to info.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/network.py to network.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/node.py to node.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/units.py to units.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/gnpy/core/utils.py to utils.cpython-36.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying gnpy.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying gnpy.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying gnpy.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying gnpy.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying gnpy.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/gnpy-0.1.3-py3.6.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing gnpy-0.1.3-py3.6.egg
Copying gnpy-0.1.3-py3.6.egg to /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Adding gnpy 0.1.3 to easy-install.pth file

Installed /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy-0.1.3-py3.6.egg
Processing dependencies for gnpy==0.1.3
Searching for xlrd==1.1.0
Best match: xlrd 1.1.0
Adding xlrd 1.1.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for sphinxcontrib-websupport==1.0.1
Best match: sphinxcontrib-websupport 1.0.1
Adding sphinxcontrib-websupport 1.0.1 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for sphinxcontrib-bibtex==0.3.6
Best match: sphinxcontrib-bibtex 0.3.6
Adding sphinxcontrib-bibtex 0.3.6 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for Sphinx==1.6.6
Best match: Sphinx 1.6.6
Adding Sphinx 1.6.6 to easy-install.pth file
Installing sphinx-apidoc script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing sphinx-autogen script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing sphinx-build script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing sphinx-quickstart script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for snowballstemmer==1.2.1
Best match: snowballstemmer 1.2.1
Adding snowballstemmer 1.2.1 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for scipy==1.0.0
Best match: scipy 1.0.0
Adding scipy 1.0.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Adding pytz 2017.3 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pytest==3.3.2
Best match: pytest 3.3.2
Adding pytest 3.3.2 to easy-install.pth file
Installing py.test script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pytest script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for Pygments==2.2.0
Best match: Pygments 2.2.0
Adding Pygments 2.2.0 to easy-install.pth file
Installing pygmentize script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pybtex-docutils==0.2.1
Best match: pybtex-docutils 0.2.1
Adding pybtex-docutils 0.2.1 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pybtex==0.21
Best match: pybtex 0.21
Adding pybtex 0.21 to easy-install.pth file
Installing pybtex script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pybtex-convert script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pybtex-format script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for py==1.5.2
Best match: py 1.5.2
Adding py 1.5.2 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for pluggy==0.6.0
Best match: pluggy 0.6.0
Adding pluggy 0.6.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for oset==0.1.3
Best match: oset 0.1.3
Adding oset 0.1.3 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for networkx==2.0
Best match: networkx 2.0
Adding networkx 2.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for matplotlib==2.1.0
Best match: matplotlib 2.1.0
Adding matplotlib 2.1.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for MarkupSafe==1.0
Best match: MarkupSafe 1.0
Adding MarkupSafe 1.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for latexcodec==1.0.5
Best match: latexcodec 1.0.5
Adding latexcodec 1.0.5 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for Jinja2==2.10
Best match: Jinja2 2.10
Adding Jinja2 2.10 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for imagesize==0.7.1
Best match: imagesize 0.7.1
Adding imagesize 0.7.1 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for docutils==0.14
Best match: docutils 0.14
Adding docutils 0.14 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for decorator==4.1.2
Best match: decorator 4.1.2
Adding decorator 4.1.2 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for certifi==2017.11.5
Best match: certifi 2017.11.5
Adding certifi 2017.11.5 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for Babel==2.5.3
Best match: Babel 2.5.3
Adding Babel 2.5.3 to easy-install.pth file
Installing pybabel script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for attrs==17.4.0
Best match: attrs 17.4.0
Adding attrs 17.4.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for alabaster==0.7.10
Best match: alabaster 0.7.10
Adding alabaster 0.7.10 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for setuptools==38.5.1
Best match: setuptools 38.5.1
Adding setuptools 38.5.1 to easy-install.pth file
Installing easy_install script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing easy_install-3.6 script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Finished processing dependencies for gnpy==0.1.3
```
```
ggrammel-mbp:gnpy ggrammel$ python examples/transmission_main_example.py
Traceback (most recent call last):
  File "examples/transmission_main_example.py", line 90, in <module>
    exit(main(args))
  File "examples/transmission_main_example.py", line 41, in main
    network = network_from_json(json_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 29, in network_from_json
    g.add_node(getattr(elements, el_config['type'])(el_config))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/elements.py", line 222, in __init__
    super().__init__(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/node.py", line 48, in __init__
    self.config = ConfigStruct(**config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/node.py", line 31, in __init__
    json_config = load_json(config['config_from_json'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/utils.py", line 20, in load_json
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'edfa_config.json'
```
```
ggrammel-mbp:gnpy ggrammel$ python examples/transmission_main_example.py examples/coronet_conus_example.json
Traceback (most recent call last):
  File "examples/transmission_main_example.py", line 90, in <module>
    exit(main(args))
  File "examples/transmission_main_example.py", line 42, in main
    build_network(network)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 119, in build_network
    network = split_fiber(network, fiber)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 86, in split_fiber
    network = add_egress_amplifier(network, prev_node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 108, in add_egress_amplifier
    new_edfa = Edfa(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/elements.py", line 222, in __init__
    super().__init__(config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/node.py", line 48, in __init__
    self.config = ConfigStruct(**config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/node.py", line 31, in __init__
    json_config = load_json(config['config_from_json'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/utils.py", line 20, in load_json
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'edfa_config.json'
ggrammel-mbp:gnpy ggrammel$ 
ggrammel-mbp:gnpy ggrammel$ ls -l examples/
total 296
-rw-r--r--   1 ggrammel  wheel  132604 Apr 16 19:19 coronet_conus_example.json
drwxr-xr-x   7 ggrammel  wheel     238 Apr 16 19:19 edfa
-rw-r--r--   1 ggrammel  wheel    9973 Apr 16 19:19 edfa_config.json
drwxr-xr-x  12 ggrammel  wheel     408 Apr 16 19:19 edfa_model
-rw-r--r--   1 ggrammel  wheel    3241 Apr 16 19:19 transmission_main_example.py
ggrammel-mbp:gnpy ggrammel$ 
```

**Comment by stevec2810** [comment]
I have this running correctly if you run it from the examples directory..running from the top level like this causes this error.

**Comment by ggrammel** [comment]
OK, that seems to work, but what is the action now

  1.  Changing the Readme or
  2.  Making sure the Readme works as-is?

**Comment by ggrammel** [comment]
2018-04-18: issue still present!
needs to be fixed with high priority as users following the Readme file experience errors which look like a broken master repository.

**Comment by ggrammel** [comment]
Fix: Replace Readme:
====================================================================
`gnpy`: mesh optical network route planning and optimization library
====================================================================

|docs| |build|

**gnpy is an open-source, community-developed library for building route planning
and optimization tools in real-world mesh optical networks.**

`gnpy <http://github.com/telecominfraproject/gnpy>`__ is:

- a sponsored project of the `OOPT/PSE <http://telecominfraproject.com/project-groups-2/backhaul-projects/open-optical-packet-transport/>`_ working group of the `Telecom Infra Project <http://telecominfraproject.com>`_.
- fully community-driven, fully open source library
- driven by a consortium of operators, vendors, and academic researchers
- intended for rapid development of production-grade route planning tools
- easily extensible to include custom network elements
- performant to the scale of real-world mesh optical networks

Documentation: https://gnpy.readthedocs.io

Installation
------------

``gnpy`` is hosted in the `Python Package Index <http://pypi.org/>`_ (`gnpy <https://pypi.org/project/gnpy/>`__). It can be installed via:

.. code-block:: shell

    $ pip install gnpy

It can also be installed directly from the repo.

.. code-block:: shell

    $ git clone https://github.com/telecominfraproject/gnpy
    $ cd gnpy
    $ python setup.py install

Both approaches above will handle installing any additional software dependencies.

    **Note**: *We recommend the use of the Anaconda Python distribution
    (https://www.anaconda.com/download) which comes with many scientific
    computing dependencies pre-installed.*

Instructions for Use
--------------------

``gnpy`` is a library for building route planning and optimization tools.

It ships with a number of example programs. Release versions will ship with
fully-functional programs.


    **Note**: *If you are a network operator or involved in route planning and
    optimization for your organization, please contact project chairs or maintainer James
    Powell <james.powell@telecominfraproject>. gnpy is looking for users with
    specific, delineated use cases to drive requirements for future
    development.*


**To get started, run the transmission example:**
  **Note**: * examples need to be launched from the examples folder*

.. code-block:: shell

    $ cd examples
    $ python transmission_main_example.py

By default, this script operates on a single span network defined in `examples/edfa/edfa_example_network.json <examples/edfa/edfa_example_network.json>`_

You can specify a different network at the command line as follows. For
example, to use the CORONET Continental US (CONUS) network defined in `examples/coronet_conus_example.json <examples/coronet_conus_example.json>`_:

.. code-block:: shell
    $ python transmission_main_example.py coronet_conus_example.json

This script will calculate the average signal osnr and snr across 93 network
elements (transceiver, ROADMs, fibers, and amplifiers) between Abilene, Texas
and Albany, New York.

This script calculates the average signal OSNR = |OSNR| and SNR = |SNR|.

.. |OSNR| replace:: P\ :sub:`ch`\ /P\ :sub:`ase`
.. |SNR| replace:: P\ :sub:`ch`\ /(P\ :sub:`nli`\ +\ P\ :sub:`ase`)

|Pase| is the amplified spontaneous emission noise, and |Pnli| the non-linear
interference noise.

.. |Pase| replace:: P\ :sub:`ase`
.. |Pnli| replace:: P\ :sub:`nli`

The `transmission_main_example.py <examples/transmission_main_example.py>`_
script propagates a specrum of 96 channels at 32 Gbaud, 50 GHz spacing and 0
dBm/channel. These are not yet parametrized but can be modified directly in the
script (via the SpectralInformation tuple) to accomodate any baud rate,
spacing, power or channel count demand.

The amplifier's gain is set to exactly compsenate for the loss in each network
element. The amplifier is currently defined with gain range of 15 dB to 25 dB
and 21 dBm max output power. Ripple and NF models are defined in
`examples/edfa_config.json <examples/edfa_config.json>`_

Contributing
------------

``gnpy`` is looking for additional contributors, especially those with experience
planning and maintaining large-scale, real-world mesh optical networks.

To get involved, please contact James Powell
<james.powell@telecominfraproject.com> or Gert Grammel <ggrammel@juniper.net>.

``gnpy`` contributions are currently limited to members of `TIP
<http://telecominfraproject.com>`_. Membership is free and open to all.

See the `Onboarding Guide
<https://github.com/Telecominfraproject/gnpy/wiki/Onboarding-Guide>`_ for
specific details on code contribtions.

See `AUTHORS.rst <AUTHORS.rst>`_ for past and present contributors.

Project Background
------------------

Data Centers are built upon interchangeable, highly standardized node and
network architectures rather than a sum of isolated solutions. This also
translates to optical networking. It leads to a push in enabling multi-vendor
optical network by disaggregating HW and SW functions and focussing on
interoperability. In this paradigm, the burden of responsibility for ensuring
the performance of such disaggregated open optical systems falls on the
operators. Consequently, operators and vendors are collaborating in defining
control models that can be readily used by off-the-shelf controllers. However,
node and network models are only part of the answer. To take reasonable
decisions, controllers need to incorporate logic to simulate and assess optical
performance. Hence, a vendor-independent optical quality estimator is required.
Given its vendor-agnostic nature, such an estimator needs to be driven by a
consortium of operators, system and component suppliers.

Founded in February 2016, the Telecom Infra Project (TIP) is an
engineering-focused initiative which is operator driven, but features
collaboration across operators, suppliers, developers, integrators, and
startups with the goal of disaggregating the traditional network deployment
approach. The group’s ultimate goal is to help provide better connectivity for
communities all over the world as more people come on-line and demand more
bandwidth- intensive experiences like video, virtual reality and augmented
reality.

Within TIP, the Open Optical Packet Transport (OOPT) project group is chartered
with unbundling monolithic packet-optical network technologies in order to
unlock innovation and support new, more flexible connectivity paradigms.

The key to unbundling is the ability to accurately plan and predict the
performance of optical line systems based on an accurate simulation of optical
parameters. Under that OOPT umbrella, the Physical Simulation Environment (PSE)
working group set out to disrupt the planning landscape by providing an open
source simulation model which can be used freely across multiple vendor
implementations.

.. |docs| image:: https://readthedocs.org/projects/gnpy/badge/?version=develop
  :target: http://gnpy.readthedocs.io/en/develop/?badge=develop
  :alt: Documentation Status
  :scale: 100%

.. |build| image:: https://travis-ci.org/mcantono/gnpy.svg?branch=develop
  :target: https://travis-ci.org/mcantono/gnpy
  :alt: Build Status
  :scale: 100%

TIP OOPT/PSE & PSE WG Charter
-----------------------------

We believe that openly sharing ideas, specifications, and other intellectual
property is the key to maximizing innovation and reducing complexity

TIP OOPT/PSE's goal is to build an end-to-end simulation environment which
defines the network models of the optical device transfer functions and their
parameters.  This environment will provide validation of the optical
performance requirements for the TIP OLS building blocks.

- The model may be approximate or complete depending on the network complexity.
  Each model shall be validated against the proposed network scenario.
- The environment must be able to process network models from multiple vendors,
  and also allow users to pick any implementation in an open source framework.
- The PSE will influence and benefit from the innovation of the DTC, API, and
  OLS working groups.
- The PSE represents a step along the journey towards multi-layer optimization.

License
-------

``gnpy`` is distributed under a standard BSD 3-Clause License.

See `LICENSE <LICENSE>`__ for more details.

**Comment by dutc** [comment]
Could you submit a pull request against the develop branch with your fixes? Thanks

**Comment by ggrammel** [comment]
simply trying to fix master asap. Don't know if the fix is applicable to the develop branch. We can probably deal with that later.

**Comment by ggrammel** [comment]
created pull request

**Comment by ggrammel** [comment]
Since pull request directly to master was rejected, I added another pull request for develop with the expectation that the README file will be pulled through into master without further delays. By following the new README it should now be possible to run gnpy examples on master without throwing errors.

**Comment by ggrammel** [comment]
seems the develop branch has now been committed to master. Did you check if the Readme now still fits to the new Example files? The README was weitten for the original master and was was not tested with develop (see above).

**Comment by ggrammel** [comment]
after some testing figured out that the solution is to set PYTHONPATH to the gnpy directory
please add this to the README so that the current master examples can run without errors

**Comment by dutc** [comment]
Cloning and running from the repo is a workflow targeting code contributors. They should already be familiar with the use of PYTHONPATH. We probably don't need to document all the details of how Python works, since we can expect that code contributors will be broadly aware of this.

The workflow for non-code contributors is to use the Binder link. If there are Binder errors, these users can submit Github issues for us to resolve (where there the cause is on the side of `gnpy`.)

**Comment by ggrammel** [comment]
Code contributors are working on their own branch and commit to develop. The issue here is related to the master branch. Master shall allow users who feel comfortable with installing python programs to run gnpy examples as described without errors. 
re-opening the issue as the action item from the PSE-Group call still needs to be addressed:
James: Examples described in README on Master branch shall work without errors. Target 2018-04-26

**Comment by ggrammel** [comment]
What has been pushed to master?

**Comment by ggrammel** [comment]
Master is supposed to be always deployable. Today Examples described in Readme on Master branch still don't work without errors. 
What kept us off fixing it and how is it planned to be addressed?
1) roll back to previous master branch and keep Readme provided two weeks ago?
2) keep current master but update Readme to avoid running into error conditions?
We should aim to  address such externally visible issues right away - in particular since they seem trivial to resolve. Keeping such things open for long doesn't inspire trust and turns folks away who wanted to try it out but run into error conditions.
A solution is overdue

**Comment by ggrammel** [comment]
Followed readme in https://github.com/Telecominfraproject/gnpy/tree/master
...
$ git clone https://github.com/telecominfraproject/gnpy
$ cd gnpy
$ python setup.py install
$ cd examples
$ python transmission_main_example.py

 and ran into the same condition as reported April 26:
```
ggrammel-mbp:examples ggrammel$ python transmission_main_example.py
Traceback (most recent call last):
  File "transmission_main_example.py", line 14, in <module>
    from gnpy.core.equipment import read_eqpt_library
ModuleNotFoundError: No module named 'gnpy.core.equipment'
```

Thought it was already fixed as reported on Tue call.
