### ISSUE TITLE
Fiber designations and parameters library

### ISSUE THREAD

**Issue by owens-bill** [Telecominfraproject/oopt-gnpy#57]
I'm filling in the model spreadsheet with info for the NYSERNet network and have come up with a few comments and questions. This one isn't specific to the spreadsheet though, so I'm separating it out.

I think we should standardize on a list of fiber names and build a library of common types. I have both Corning LEAF (which could be called NZDSF or G.655) and generic SMF-28 (which could also be called SMF, SSMF, or G.652). Other networks would likely have one or both of those types, but could have specific manufacturers' products as well, with somewhat different characteristics.

There's also a question in my mind about how precise our fiber parameters will be, and whether it's good to have specific manufacturer numbers or just generic, and therefore approximate values. I think there should also be a simple mechanism for adding new fiber types, which is one of the reasons I suggest making this a specific data store rather than burying it in the code.

**Comment by jeanluc-auge** [comment]
Both json and xls topology files now reads amplifier and fiber parameters from a json library:
gnpy/examples/eqpt_config.json
you can define new amplifier types just by specifying 
name ('type_variety')
max_gain ('gain_flatmax')
min_gain ('gain_min')
nf @ max_gain ('nf_min')
nf @ min_gain ('nf_max')
and new fiber types just by specifying
name ('type_variety')
dispersion (s/m) ('dispersion')
gamma (/m) ('gamma')
If you have specific fiber types for which you know the dispersion and gamma coefficient I'd be happy to enter them in the eqpt_config.json file and incorporate them in my next PR
or feel free to do your own pull request.
Thank you

**Comment by owens-bill** [comment]
One more observation on this point - I don’t know what other fiber parameters we might need to know for future functions, is it difficult to add them later, or should we try to incorporate as many different parameters as we can, from the start?

**Comment by dutc** [comment]
We can add fiber parameters as needed.
