### ISSUE TITLE
ROADM loss

### ISSUE THREAD

**Issue by berahtlv** [Telecominfraproject/oopt-gnpy#63]
At the moment development version for ROADMs has only one loss parameter and from example can be understood that this is express channel loss (Preamp -> filter_structure -> Booster).

If Transceiver is defined in ROADM network element (parsed .xls) its transmit power is attenuated by this express_loss and that influences Booster type and its amplification target.

Practically there are at least two types of losses:
- express channel loss ("Preamp -> filter_structure -> Booster")
- add/drop channel loss ("filter_structure -> Booster" and "Preamp -> filter_structure")

Additionally it will usable to use Booster-less amplifiers (#62).

**Comment by jeanluc-auge** [comment]
Thank you for your input, you are absolutely right, 
however: 
* from a performance modelling point of view, what matters is the channel power (Pch) at the input of the ROADM egress amplifier
* the ROADM equalization property means that this power is the same for add&drop and express channels

*Currently, in the code:*

* the add&drop channel power at the egress amplifier input is the [Tx tupple power](https://github.com/Telecominfraproject/gnpy/blob/master/examples/transmission_main_example.py#L86) minus the [ROADM loss](https://github.com/Telecominfraproject/gnpy/blob/master/gnpy/core/elements.py#L81) (that should be read from the json input in future code evolutions).
* and the express channel power is the same [Tx tupple power](https://github.com/Telecominfraproject/gnpy/blob/master/examples/transmission_main_example.py#L86) minus the ROADM loss *if all previous amplifiers gain have been set to just compensate network element losses*.

=> Therefore, as long as the amplfier gains are automatically set by the code (not user input), there is no issue. 
=> Even when we are going to code automatic gain setting that does not just compensate for previous span loss (but instead targets the optimum launched power vs span loss), it is just a matter of having Pch at the ROADM ingress amplifier output = Tx tupple power.
=> There is a risk if amplifier gains are user inputs but it's the responsability of the user to calculate that powers @ the input of the egress amplifier are the same for add& drop and express channel. Adding an add&drop loss will:
* not avoid this calculation, albeit it would make it more equipment like
* not change the SNR calculation, as explained at the beginning
