### ISSUE TITLE
Issue from Bell labs

### ISSUE THREAD

**Issue by vittoriocurri** [Telecominfraproject/oopt-gnpy#72]
Following-up an email from a collegue at Bell labs, I've given some instructions on how to download 
gnpy. Then, I've received the e-mail message I'm posting in the following. In my opinion, the arised issues may be of general interest, and it could be worth to discuss them.
Vittorio
--------------------------------------------------------------------------------------------------------
One of my managers followed your instructions for downloading and running the tool. He had the following questions and issues:

1. There is very little if any documentation on the website. Can you point to any documentation?
2. He could find no description of the various Tx/Rx types that can be simulated.
3. There is nothing about the constellation.
4. He asked if you have a model of m-QAM modulation that he can try out.

**Comment by berahtlv** [comment]
As I understood:

Basics are described in README.
GNpy is using generalized simulation model, all is defined by frequency. Transceiver calculates SNR values based on received SpectralInformation which is recalculated in each Node.

At the moment transmitter SpectralInformation can be modified directly in transmission_main_example.py:

* master branch:

```
...
spacing = 0.05 #THz
si = SpectralInformation() # !! SI units W, Hz
si = si.update(carriers=tuple(Channel(f, (191.3+spacing*f)*1e12, 
        32e9, 0.15, Power(1e-3, 0, 0)) for f in range(1,97)))
...
```
default - 96 frequencies (starting from 191.3THz) with 50GHz spacing at 0dBm (1mW) power and 32GHz wide channel.

* develop branch:
```
...
for p in range(3,4): #change range to sweep results across several powers
    p=db2lin(p)*1e-3
    spacing = 0.05 #THz
    si = SpectralInformation() # !! SI units W, Hz
    si = si.update(carriers=tuple(Channel(f, (191.3+spacing*f)*1e12, 
            32e9, 0.15, Power(p, 0, 0)) for f in range(1,80)))
...
```        
default - 79 frequencies (starting from 191.3THz) with 50GHz spacing at 3dBm power and 32GHz wide channel.


Simulation calculates receiver SNR value which shoud be different for different modulation formats. Example uses 32GHz channel that stands for:
* 128Gbps @ DP-QPSK modulation, receiver OSNR threshold about 13dB/0.1nm
* 256Gbps @ DP-16QAM modulation, receiver OSNR threshold about 20dB/0.1nm

**Comment by EstherLerouzic** [comment]
dear @vittoriocurri 
Here are answers to some of your remarks:
point1 : additionnal documentation has been added [https://github.com/Telecominfraproject/oopt-gnpy/blob/develop/Excel_userguide.rst](url). Do not hesitate to open another issue on documentation or to contribute on the file!
point2 : We have recently added the transceiver library in [https://github.com/Telecominfraproject/oopt-gnpy/blob/develop/examples/eqpt_config.json](url). The path_requests_run.py [https://github.com/Telecominfraproject/oopt-gnpy/blob/develop/examples/path_requests_run.py] use it.
We plan to add the transceiver feature also in the transmission_main_example.py
hope it helps!
regards
