### ISSUE TITLE
 dbkm_2_lin error

### ISSUE THREAD

**Issue by nigulasikaochuan** [Telecominfraproject/oopt-gnpy#78]
in the class Fiber,the bounded method  def dbkm_2_lin(self):.... may be error. the linear alpha = （nonlinear alpha）/10/log10（e）(1/km),

**Comment by jeanluc-auge** [comment]
Thank you for looking and checking into the code.
The 2 conventions exist, it doesn't matter as long as there is consistency:
=> If you look in the code at how is used the lin_loss_coef in the [asymptotic_length](https://github.com/Telecominfraproject/oopt-gnpy/blob/04c479519273734f60c5196060765b33c2f834f3/gnpy/core/elements.py#L182) or [effective_length](https://github.com/Telecominfraproject/oopt-gnpy/blob/04c479519273734f60c5196060765b33c2f834f3/gnpy/core/elements.py#L176) properties, you can see that the factor 2 is accouonted for, for example in [leff calculation](https://github.com/Telecominfraproject/oopt-gnpy/blob/04c479519273734f60c5196060765b33c2f834f3/gnpy/core/elements.py#L178)
