### ISSUE TITLE
lin_loss _coeff error

### ISSUE THREAD

**Issue by nigulasikaochuan** [Telecominfraproject/oopt-gnpy#79]
![image](https://user-images.githubusercontent.com/34807360/41220818-248898d2-6d95-11e8-8a1c-20ae2c529044.png)

i think this may be wrong
self.lin_loss_coef = self.params.loss_coef / (20*np.log10(np.exp(1)))
correct should be：
self.lin_loss_coef = self.params.loss_coef / (10*np.log10(np.exp(1)))

**Comment by jeanluc-auge** [comment]
see answer to #78
