### ISSUE TITLE
transmission_main_example.py does not seem to work anymore with CORONET_Global_Topology.xls file

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#86]
- some input nodes are no more accepted
python3 examples/transmission_main_example.py examples/CORONET_Global_Topology.xls Abilene Dallas is raising an stopIteration error although it is defined as a link: probably because all no nodes type are given and 2 degree nodes are set as ILA by default
-> Question: should we keep this example working ? or can we change it and add required type info on Nodes sheet ?

- amplifiers are not correctly inserted at the end of spans during build_network
I could not find why...

here is an example:
python3 examples/transmission_main_example.py examples/CORONET_Global_Topology.xls dallas houston

invalid node type (ILA) specified in Dallas, replaced by ROADM
invalid node type (ILA) specified in El_Paso, replaced by ROADM
invalid node type (ILA) specified in Syracuse, replaced by ROADM
invalid node type (ILA) specified in Albuquerque, replaced by ROADM
invalid node type (ILA) specified in Denver, replaced by ROADM
invalid node type (ILA) specified in Las_Vegas, replaced by ROADM
invalid node type (ILA) specified in Amsterdam, replaced by ROADM
invalid node type (ILA) specified in New_York, replaced by ROADM
invalid node type (ILA) specified in Atlanta, replaced by ROADM
invalid node type (ILA) specified in Birmingham, replaced by ROADM
invalid node type (ILA) specified in Jacksonville, replaced by ROADM
invalid node type (ILA) specified in Houston, replaced by ROADM
invalid node type (ILA) specified in Baltimore, replaced by ROADM
invalid node type (ILA) specified in Philadelphia, replaced by ROADM
invalid node type (ILA) specified in Pittsburgh, replaced by ROADM
invalid node type (ILA) specified in Washington_DC, replaced by ROADM
invalid node type (ILA) specified in Delhi, replaced by ROADM
invalid node type (ILA) specified in Hong_Kong, replaced by ROADM
invalid node type (ILA) specified in New_Orleans, replaced by ROADM
invalid node type (ILA) specified in Warsaw, replaced by ROADM
invalid node type (ILA) specified in Billings, replaced by ROADM
invalid node type (ILA) specified in Nashville, replaced by ROADM
invalid node type (ILA) specified in Minneapolis, replaced by ROADM
invalid node type (ILA) specified in London, replaced by ROADM
invalid node type (ILA) specified in Istanbul, replaced by ROADM
invalid node type (ILA) specified in Cleveland, replaced by ROADM
invalid node type (ILA) specified in Raleigh, replaced by ROADM
invalid node type (ILA) specified in Greensboro, replaced by ROADM
invalid node type (ILA) specified in Chicago, replaced by ROADM
invalid node type (ILA) specified in Cincinnati, replaced by ROADM
invalid node type (ILA) specified in Columbus, replaced by ROADM
invalid node type (ILA) specified in Louisville, replaced by ROADM
invalid node type (ILA) specified in Mumbai, replaced by ROADM
invalid node type (ILA) specified in Omaha, replaced by ROADM
invalid node type (ILA) specified in Salt_Lake_City, replaced by ROADM
invalid node type (ILA) specified in Vienna, replaced by ROADM
invalid node type (ILA) specified in Fresno, replaced by ROADM
invalid node type (ILA) specified in Los_Angeles, replaced by ROADM
invalid node type (ILA) specified in Oakland, replaced by ROADM
invalid node type (ILA) specified in Sydney, replaced by ROADM
invalid node type (ILA) specified in Taipei, replaced by ROADM
invalid node type (ILA) specified in Honolulu, replaced by ROADM
invalid node type (ILA) specified in Rome, replaced by ROADM
invalid node type (ILA) specified in Kansas_City, replaced by ROADM
invalid node type (ILA) specified in St_Louis, replaced by ROADM
invalid node type (ILA) specified in Phoenix, replaced by ROADM
invalid node type (ILA) specified in Paris, replaced by ROADM
invalid node type (ILA) specified in Miami, replaced by ROADM
invalid node type (ILA) specified in Scranton, replaced by ROADM
invalid node type (ILA) specified in Portland, replaced by ROADM
invalid node type (ILA) specified in Tokyo, replaced by ROADM
invalid souce node specified, did you mean:                  
['trx Dallas']?                  
'dallas', replaced with trx Dallas
invalid destination node specified, did you mean:                
['trx Houston']?                
'houston', replaced with trx Houston

There are 4 fiber spans over 1730924m between trx Dallas and trx Houston

Now propagating between trx Dallas and trx Houston:

Propagating with input power = 0.00dBm :
Transceiver trx Dallas
Roadm roadm Dallas
  loss (dB): 20.00
Edfa Edfa0_roadm Dallas
  type_variety:      test
  gain (dB):         20.00
  noise figure (dB): 6.40
  Power In (dBm):    -0.18
  Power Out (dBm):   19.83
Fiber fiber (Dallas → Houston)-_(0/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(1/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(2/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(3/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Roadm roadm Houston
  loss (dB): 20.00
Transceiver trx Houston

Transmission result for input power = 0.00dBm :
Transceiver trx Houston

**Comment by stevec2810** [comment]
try like this. it worked for me.

python3.6 transmission_main_example.py coronet_conus_example.json 'trx Dallas' 'trx Memphis'

**Comment by dutc** [comment]
There's a `-l` parameter which lists the possible source and sink nodes.
```
$ python transmission_main_example.py CORONET_Global_Topology.json -l
```

As @stevec2810 notes above, you have to specify "trx Dallas" or "trx Paris." We can fix this once we have tests in place.

To answer your other questions:
- we should definitely keep this example working. I am currently adding some tests around this example in order to ensure that our CI can flag issues.
- can you identify some of the missing amplifiers? We can add some tests to help us figure out why these are missing.

**Comment by EstherLerouzic** [comment]
thanks for the answer!
the 'trx' is not needed in general (an automatic trx completion has been done to improve useability). For example, this test : 
     python3 examples/transmission_main_example.py examples/CORONET_Global_Topology.xls dallas houston  
does not raise stopIteration. 
"
invalid souce node specified, did you mean:                  
['trx Dallas']?                  
'dallas', replaced with trx Dallas
invalid destination node specified, did you mean:                
['trx Houston']?                
'houston', replaced with trx Houston
There are 4 fiber spans over 1730924m between trx Dallas and trx Houston

Now propagating between trx Dallas and trx Houston:

Propagating with input power = 0.00dBm :
Transceiver trx Dallas
Roadm roadm Dallas
  loss (dB): 20.00
Edfa Edfa0_roadm Dallas
  type_variety:      test
  gain (dB):         20.00
  noise figure (dB): 6.40
  Power In (dBm):    -0.18
  Power Out (dBm):   19.83
Fiber fiber (Dallas → Houston)-_(0/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(1/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(2/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Fiber fiber (Dallas → Houston)-_(3/4)
  type_variety: SSMF
  length (m):   432731.00
  loss (dB):    87.55
  (includes conn loss (dB) in: 0.50 out: 0.50)
Roadm roadm Houston
  loss (dB): 20.00
Transceiver trx Houston

Transmission result for input power = 0.00dBm :
Transceiver trx Houston
"
___

I really think that some nodes of CORONET topology are read as ILA instead of ROADM because they are 2 degree ROADM . the implicit decision of type does not provide the expected result, in this particular case.
there should be an amplifier at the end of each fiber spans.
It means that the build_network should not result in the previous nodes succession:
after: "Fiber fiber (Dallas → Houston)-_(0/4)" and before "Fiber fiber (Dallas → Houston)-_(1/4)"
there should be an amplifier site.

**Comment by jeanluc-auge** [comment]
I'm on it, thanks.
it's a side effect of the recent refactor => I will issue a bug fix this week

**Comment by dutc** [comment]
Let's also make sure we have some minimal code coverage to accompany the fix. Thanks!

**Comment by jeanluc-auge** [comment]
bug is fixed, 
I 'll push tomorrow alongs side the power management
