### ISSUE TITLE
plot feature does not seem to work in every cases on transmission_main_example.py

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#88]
When trying -p option on develop branch, it does not work for meshTopologyExampleV2.xls or json, CORONET_Global_Topology.xls or json
It works with the edfa_example_network.json

python3 transmission_main_example.py -p meshTopologyExampleV2.xls 'trx Lannion_CAS' 'trx Lorient_KMA'
There are 3 fiber spans over 130000m between trx Lannion_CAS and trx Lorient_KMA
Now propagating between trx Lannion_CAS and trx Lorient_KMA:
Porpagating with input power = 0.00dBm :
Transceiver trx Lannion_CAS
Roadm roadm Lannion_CAS
  loss (dB): 20.00
Edfa Edfa0_roadm Lannion_CAS
  type_variety:      test
  gain (dB):         20.00
  noise figure (dB): 6.40
  Power In (dBm):    -0.18
  Power Out (dBm):   19.83
Fiber fiber (Lannion_CAS → Corlay)-F061
  type_variety: SSMF
  length (m):   20000.00
  loss (dB):    4.00
Fused ingress fused spans in Corlay
  loss (dB): 1.00
Fiber fiber (Corlay → Loudeac)-F010
  type_variety: SSMF
  length (m):   50000.00
  loss (dB):    10.00
Fused ingress fused spans in Loudeac
  loss (dB): 1.00
Fiber fiber (Loudeac → Lorient_KMA)-F054
  type_variety: SSMF
  length (m):   60000.00
  loss (dB):    12.00
Edfa Edfa0_fiber (Loudeac → Lorient_KMA)-F054
  type_variety:      std_medium_gain
  gain (dB):         28.00
  noise figure (dB): 5.97
  Power In (dBm):    -8.17
  Power Out (dBm):   19.88
Roadm roadm Lorient_KMA
  loss (dB): 20.00
Transceiver trx Lorient_KMA
  OSNR ASE (1nm):        23.27
  OSNR ASE (signal bw):  19.19
  SNR total (signal bw): 19.03

Transmission result for input power = 0.00dBm :
Transceiver trx Lorient_KMA
  OSNR ASE (1nm):        23.27
  OSNR ASE (signal bw):  19.19
  SNR total (signal bw): 19.03
Traceback (most recent call last):
  File "transmission_main_example.py", line 141, in <module>
    plot_results(network, path, source, sink)
  File "transmission_main_example.py", line 30, in plot_results
    pos = {n: (n.lng, n.lat) for n in network.nodes()}
  File "transmission_main_example.py", line 30, in <dictcomp>
    pos = {n: (n.lng, n.lat) for n in network.nodes()}
  File "/home/user/workspace/TIP/gnpy/gnpy/core/node.py", line 47, in longitude
    return self.location.longitude
  File "/home/user/workspace/TIP/gnpy/gnpy/core/node.py", line 42, in location
    return self.metadata['location']
TypeError: 'NoneType' object is not subscriptable

**Comment by dutc** [comment]
The plotting will fail if the input data does not include geographic locations. 

Geographic information (latitude, longitude) for each node is optional, since it's only used for plotting.

If you add lat/long values to the input data file, the plotting should work.

**Comment by ggrammel** [comment]
to be checked before next master release

**Comment by dutc** [comment]
This should be resolved in the latest PR.
