### ISSUE TITLE
Suggested improvement of README

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#93]
2018-07-21

README:
- installation from repo OK
- set PYTHONPATH variable as described. Consider moving the text in front of example: 
“You may need to set PYTHONPATH variable. For example on Ubuntu, add your workspace path to PYTHONPATH in your .bashrc file:
export PYTHONPATH=$PYTHONPATH:~/<workspace path>/gnpy/“

**Comment by dutc** [comment]
We'll take a look into improving some of the documentation after the next master release.

**Comment by ggrammel** [comment]
I am sure the users would appreciate improvements before the next master release.

**Comment by dutc** [comment]
Fixed in version 1.0.
