### ISSUE TITLE
installing gnpy option doesn't allow to follow rest of readme

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#98]
2018-08-01
Readme says:
   gnpy is hosted in the Python Package Index (gnpy). It can be installed via:
   $ pip3 install gnpy
   This will install the current (tagged) release version.

further down, Readme then continues with:
   To get started, run the transmission example:
       Note: Examples should be run from the examples/ folder.
   $ cd examples
   $ python transmission_main_example.py

However if gnpy was installed with pip3, there is no "examples" directory.

Simple fix would be to remove the first statement from Readme and only leave the "Alternative" way to install for now. 
Another possibility is to add verbiage about requiring the alternative installation procedure to run through the examples.

labeled as bug in Readme, no code changes needed.

**Comment by dutc** [comment]
Resolved.
